### ISSUE TITLE
EnumMember values cannot be different casing

### ISSUE THREAD

**Issue by russcam** [JamesNK/Newtonsoft.Json#1067]
Json.Net version: 9.0.1

[We have an enum](https://github.com/elastic/elasticsearch-net/blob/5.x/src/Nest/Ingest/Processors/DateIndexNameProcessor.cs#L129-L146) that is serialized to a string, using the `EnumMemberAttribute` to specify the serialized value. Two different enum values, `Month` and `Minute`, serialize to the same string, differing only in casing (`M` and `m`, respectively).

Json.NET throws an exception when attempting to serialize an enum that has `EnumMember` values that differ only in casing. A simple example that reproduces this

```c#
void Main()
{
    JsonConvert.SerializeObject(TimeUnit.Month).Dump();
}

[JsonConverter(typeof(StringEnumConverter))]
public enum TimeUnit
{
    [System.Runtime.Serialization.EnumMember(Value = "M")]
    Month,

    [System.Runtime.Serialization.EnumMember(Value = "m")]
    Minute
}
```

throws the following exception (with stacktrace):

> Enum name 'm' already exists on enum 'TimeUnit'.
>
>   at Newtonsoft.Json.Utilities.EnumUtils.InitializeEnumType(Type type)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.AddValue(TKey key)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get(TKey key)
   at Newtonsoft.Json.Utilities.EnumUtils.ToEnumName(Type enumType, String enumText, Boolean camelCaseText)
   at Newtonsoft.Json.Converters.StringEnumConverter.WriteJson(JsonWriter writer, Object value, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(JsonWriter writer, JsonConverter converter, Object value, JsonContract contract, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value)
   at UserQuery.Main()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Digging into the source, [the culprit seems to be the initialization of the `BidirectionalDictionary<string, string>` with an `OrdinalIgnoreCase` string comparer in `EnumUtils.InitializeEnumType` for the second item, the EnumMember value, in the BidirectionalDictionary:](https://github.com/JamesNK/Newtonsoft.Json/blob/a0403492ad79398be8d97979acae00a2aca4dfdd/Src/Newtonsoft.Json/Utilities/EnumUtils.cs#L45-L47)

```c#
  internal static class EnumUtils
  {
    private static readonly ThreadSafeStore<Type, BidirectionalDictionary<string, string>> EnumMemberNamesPerType = new ThreadSafeStore<Type, BidirectionalDictionary<string, string>>(new Func<Type, BidirectionalDictionary<string, string>>(EnumUtils.InitializeEnumType));

	private static BidirectionalDictionary<string, string> InitializeEnumType(Type type)
	{
		BidirectionalDictionary<string, string> bidirectionalDictionary = new BidirectionalDictionary<string, string>((IEqualityComparer<string>) StringComparer.OrdinalIgnoreCase, (IEqualityComparer<string>) StringComparer.OrdinalIgnoreCase);
		foreach (FieldInfo field in type.GetFields())
		{
		string name = field.Name;
		string second = field.GetCustomAttributes(typeof (EnumMemberAttribute), true).Cast<EnumMemberAttribute>().Select<EnumMemberAttribute, string>((Func<EnumMemberAttribute, string>) (a => a.Value)).SingleOrDefault<string>() ?? field.Name;
		string first;
		if (bidirectionalDictionary.TryGetBySecond(second, out first))
			throw new InvalidOperationException("Enum name '{0}' already exists on enum '{1}'.".FormatWith((IFormatProvider) CultureInfo.InvariantCulture, (object) second, (object) type.Name));
		bidirectionalDictionary.Set(name, second);
		}
		return bidirectionalDictionary;
	}
    
        // ... rest of class
}
```

Changing this to be `StringComparer.Ordinal` I think would work, however, it would break deserialization of an enum that uses `EnumMember` values **and** also uses a `StringEnumConverter` with `CamelCaseText = true`, since the resolved EnumMember value is also camel cased upon serialization.

**Comment by JamesNK** [comment]
Thanks. Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/b2afa9d674f4dc0d5137ce6f175e06e565fc66f5
