### ISSUE TITLE
Deserialization of F# Lists breaks with FSharp Core version 1.0.0-rc-170122

### ISSUE THREAD

**Issue by markvincze** [JamesNK/Newtonsoft.Json#1210]
The following code

```
type Dummy = { Field : string }

Module Test =
    let ListSerializationTest
        let json = """
        [
            {
                "Field": "foo"
            }
        ]
        """

        JsonConvert.DeserializeObject<Dummy list>(json)
```

throws the following error.

```
Newtonsoft.Json.JsonSerializationException : Cannot create and populate list type Microsoft.FSharp.Collections.FSharpList`1[MyProject.Dummy]. Path '', line 2, position 9.
      Stack Trace:
           at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewList(JsonReader reader, JsonArrayContract contract, Boolean& createdFromNonDefaultCreator)
           at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
           at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
           at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
           at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
           at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
```

This happens if I upgrade the version of the package `Microsoft.FSharp.Core.netcore` to `1.0.0-rc-170122`. With version `1.0.0-alpha-160629` it works.

**Comment by JamesNK** [comment]
Already fixed https://github.com/JamesNK/Newtonsoft.Json/issues/1180
