### ISSUE TITLE
InvalidCastException when populating an object that implements IEnumerable<T>

### ISSUE THREAD

**Issue by MaxKot** [JamesNK/Newtonsoft.Json#1234]
An InvalidCastException is throw when deserializing an object with a specific conditions.

There is a class EnumerableLike that:
1. implements IEnumerable<T>
2. is deserialized with a custom JsonConverter.

There is a class Container that:
1. has a read-only property EnumerableLikeProp of type EnumerableLike
2. has a constructor marked with JsonContructorAttribute
3. the constructor accepts JsonProperties other than EnumerableLikeProp
4. the constructor does not accept a JsonProperty for EnumerableLikeProp.

If these conditions are met then an InvalidCastException is throw when deserializing an instance of type Container.

While this is easily fixed by applying JsonObjectAttribute to the EnumerableLike class, the exception does not provide a clear description of its reasons.

Stack trace:
```
Result StackTrace:	
at Void .ctor(System.Collections.Generic.ICollection`1[System.Int32])(Object[] )
at Newtonsoft.Json.Serialization.JsonArrayContract.CreateWrapper(Object list) in D:\Newtonsoft.Json\Src\Newtonsoft.Json\Serialization\JsonArrayContract.cs:line 292
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id) in D:\Newtonsoft.Json\Src\Newtonsoft.Json\Serialization\JsonSerializerInternalReader.cs:line 2038
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator) in D:\Newtonsoft.Json\Src\Newtonsoft.Json\Serialization\JsonSerializerInternalReader.cs:line 2277
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) in D:\Newtonsoft.Json\Src\Newtonsoft.Json\Serialization\JsonSerializerInternalReader.cs:line 479
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) in D:\Newtonsoft.Json\Src\Newtonsoft.Json\Serialization\JsonSerializerInternalReader.cs:line 294
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in D:\Newtonsoft.Json\Src\Newtonsoft.Json\Serialization\JsonSerializerInternalReader.cs:line 196
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) in D:\Newtonsoft.Json\Src\Newtonsoft.Json\JsonSerializer.cs:line 874
at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType) in D:\Newtonsoft.Json\Src\Newtonsoft.Json\JsonSerializer.cs:line 853
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) in D:\Newtonsoft.Json\Src\Newtonsoft.Json\JsonConvert.cs:line 812
at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) in D:\Newtonsoft.Json\Src\Newtonsoft.Json\JsonConvert.cs:line 769
at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value) in D:\Newtonsoft.Json\Src\Newtonsoft.Json\JsonConvert.cs:line 706
at Newtonsoft.Json.Tests.JsonConvertTest.ShouldNotPopulateReadOnlyEnumerableObjectWithNonDefaultConstructor() in D:\Newtonsoft.Json\Src\Newtonsoft.Json.Tests\JsonConvertTest.cs:line 1638
Result Message:	System.InvalidCastException : Unable to cast object of type 'EnumerableWithConverter' to type 'System.Collections.Generic.ICollection`1[System.Int32]'.
```

**Comment by MaxKot** [comment]
I created pull request #1235 with the tests demonstrating the issue.

**Comment by JamesNK** [comment]
Thanks for the example. Fixed.
