### ISSUE TITLE
JObject.ToObject fails on .NET 4.5.1, but not .NET Core with custom JsonSerializer

### ISSUE THREAD

**Issue by cdavid** [JamesNK/Newtonsoft.Json#1282]
Hi

I am running into an issue where the JObject.ToObject method works on .NET Core, but fails on .NET 4.5.1. 

In particular, I am trying to deserialize from JSON an exception with a custom Exception converter. The code is here: [Gist](https://gist.github.com/cdavid/f353db6d1c145c224809c2c44fd3f073)

This works fine on .NET Core 1.0 and 1.1, but throws an exception on .NET 4.5.1. 

The exception is:
```
    Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Current JsonReader item is not an object: Null. Path '', line 5, position 24.
    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
    at net451.Program.ExceptionConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\Users\catalda\Documents\Visual Studio 2015\Projects\Diagnostics\src\net451\Program.cs:line 68
    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializableItem(JToken token, Type type, JsonISerializableContract contract, JsonProperty member)
    at Newtonsoft.Json.Serialization.JsonFormatterConverter.Convert(Object value, Type type)
    at System.Runtime.Serialization.SerializationInfo.GetValue(String name, Type type)
    at System.Exception..ctor(SerializationInfo info, StreamingContext context)
    at Void .ctor(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)(Object[] )
    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializable(JsonReader reader, JsonISerializableContract contract, JsonProperty member, String id)
    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
    at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
    at net451.Program.TestJsonConvert() in C:\Users\catalda\Documents\Visual Studio 2015\Projects\Diagnostics\src\net451\Program.cs:line 42
    at net451.Program.Main(String[] args) in C:\Users\catalda\Documents\Visual Studio 2015\Projects\Diagnostics\src\net451\Program.cs:line 13
```

**Comment by cdavid** [comment]
OK, dug a bit more, in the original file, it seems to be complaining about this particular line in the exception: ` ""InnerException"": null,`

**Comment by JamesNK** [comment]
It is because .NET 4.5.1 deserializes all members.
.NET Core 1.x does not because Exception does not implement ISerializable.
