### ISSUE TITLE
NewtonSoft is not able to serialize integers 0008 and 0009 when passed in this format.

### ISSUE THREAD

**Issue by SayanGhose** [JamesNK/Newtonsoft.Json#1385]
Our request -

{
  "TransactionDate": "2017-04-09T18:45:15.0000000-05:00",
  "Channel": "CONSUMER EXCHANGE",
  "Note": "Perform Exit Routing",
  "PartnerTrackingReference": "PTRF124402086333",
  "PlantCode": "4407",
  "InventoryAdjustmentLineItems": [
    {
      "LineItemNumber": 1,
      "TransactionType": "Inventory Mvt",
      "BusinessCode": "INV_MVT",
      "Material": "5HX-00001",
    "SerialNumbers": [
        "12345"
      ],
      "Quantity": 1,
      "StorageLocation": "0010",
      "DestinationStorageLocation" : "9020",
      "ReasonCode": 0008,
      "RecieveSKU": ""
    }

The issue -

Not working, Newtonsoft is not able to identify 0008 as number 8, same with the case reason code 0009.

Note that this works fine when we pass 0000 to 0007, the problem only happens when 8 and 9 are involved. 0010 is processed as '8'.

Example of error that we are seeing -

When we try to deserialize explicitly with Newtonsoft, noticing below error and stack trace.

“Input string '0008' is not a valid number. Path 'InventoryAdjustmentLineItems[0].ReasonCode', line 19, position 24.”

Stack trace for above error.
at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments)
   at Newtonsoft.Json.Linq.JTokenWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJObject(JsonReader reader)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value)
   at ConsoleApp1.Program.Main(String[] args) in C:\VSTSWorkspace\1DSC\InventoryAdjustment\Source\Inventory\ConsoleApp1\Program.cs:line 39

**Comment by TylerBrinkley** [comment]
I believe Json.NET treats integral numbers with leading zeroes as octal instead of decimal.

**Comment by JonHanna** [comment]
Yes, Json.NET, as with some other JSON parsers, is liberal in that it allows leading zeros before numbers that are all in the range [0-7], and treats them as octal, to match the sort of results one would get using `eval` in javascript.

The JSON standard bans leading zeros in any case other than the integer zero or where zero is immediately followed by a decimal point.

**Comment by JamesNK** [comment]
Correct.

Either trim leading zeros or surround the value with quotes to make it a string.
