### ISSUE TITLE
Can't deserialize NodaTime.Instant as Dictionary Key

### ISSUE THREAD

**Issue by stevenguh** [JamesNK/Newtonsoft.Json#1398]
This issue has been post on stackoverflow https://stackoverflow.com/questions/13941349/how-to-deserialize-a-dictionary-with-nodatime-instant-using-json-net-without-get,
and is tracked https://github.com/nodatime/nodatime.serialization/issues/2

I am wondering if the fix should be in this repo or in Noda.Serialization. I am speculating that Json.NET serializes the key and value of a Dictionary differently. Hence, the way Json.NET reconstruct the Dictionary back.

When we use a JsonConverter, it seems like it's only applicable to the value of the dictionary, but not the key of the dictionary when serialize/deserialize.

### Source/destination types

```csharp
Dictionary<Instant, Instant>
```

### Source/destination JSON

```javascript
{"2012-01-02T03:04:05Z":"2012-01-02T03:04:05.0000001Z"}
```

### Expected behavior

1. The serialized key and value has the same format
2. Json.NET can deserialize the JSON back to a `Dictionary<Instant, Instant>`

### Actual behavior

There are two issues

1. The key didn't serialize as extended format like the value does
2. Json.NET cannot deserialize back to `Dictionary<Instant, Instant>`
```
Newtonsoft.Json.JsonSerializationException: Could not convert string '2012-01-02T03:04:05Z' to dictionary key type 'NodaTime.Instant'. Create a TypeConverter to convert from the string to the key type object. Path '2012-01-02T03:04:05Z', line 1, position 24. ---> Newtonsoft.Json.JsonSerializationException: Error converting value "2012-01-02T03:04:05Z" to type 'NodaTime.Instant'. Path '2012-01-02T03:04:05Z', line 1, position 24. ---> System.ArgumentException: Could not cast or convert from System.String to NodaTime.Instant.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonConverter[] converters)
   at Program.Main(String[] args)
```

### Steps to reproduce
1. Install NodaTime, and NodaTime.Serialization from NuGet
2. Run the program below
```csharp
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using NodaTime;
using NodaTime.Serialization.JsonNet;

internal class Program
{
    private static void Main(string[] args)
    {
        JsonConverter[] converters = { NodaConverters.IntervalConverter, NodaConverters.InstantConverter };

        Instant testTime = Instant.FromUtc(2012, 1, 2, 3, 4, 5).PlusTicks(1);
        var dictionary = new Dictionary<Instant, Instant> {
            { testTime, testTime }
        };

        var json = JsonConvert.SerializeObject(dictionary, Formatting.None, converters);
        Console.WriteLine(json);
        var result = JsonConvert.DeserializeObject<Dictionary<Instant, Instant>>(json, converters);
    }
}
```

**Comment by JamesNK** [comment]
The error message tells you what you need: a TypeConverter

**Comment by stevenguh** [comment]
I guess you are basically saying the key of a dictionary should always be using TypeConverter independent of how the value of a dictionary can be serialized with a JsonConverter. And that's by design?

Also, If I am not mistaken. That TypeConverter has to be annotated on the actual implementation of the actual class like 
```
[TypeConverter(typeof(InstantConverter))]
public class Instant { .. } 
```

Base on how NodaTime is structured, I would assume this change will need to go to the main repo instead of the NodaTime.Serialziation if we are saying that's the serialization of the key is different than the value is by design. (Hence, this is not a bug in Json.NET itself?)

**Comment by TylerBrinkley** [comment]
See issue #915 and the now closed associated PR #1141. That PR could have fixed this problem for you but it has since been closed.

**Comment by stevenguh** [comment]
Base on the PR, I will assume there is current no way to tell Json.NET use external TypeConverter other than annotate directly on the class/struct.

It seems like we should have the ability to specify how to serialize the key of a dictionary.

**Comment by JamesNK** [comment]
You can wire up a converter without using an attribute like this: https://stackoverflow.com/a/13924583

**Comment by stevenguh** [comment]
In order to customize the serialization of a Dictionary key, we will have to
1. Define a TypeConverter for that type
2. Annotate the type with the TypeConverter or do https://stackoverflow.com/a/13924583 if there is no control on the actual class/struct

Do you think Json.NET will add the ability to provide dictionary key serialization mechanism other than annotating TypeConverter on the type (basically step 2)?

If not, then I will assume this is not something that Json.NET will consider an issue or bug, and we probably should close this bug?

**Comment by JamesNK** [comment]
Yes.

There is no dependency between a TypeConverter and Json.NET so you don't really need to have the TypeConverter being in a separate NuGet package. Just think of the TypeConverter as a nice way to convert to and from a string (converting to a string can just call the ToString).
