### ISSUE TITLE
PlatformNotSupportedException when serializing some ISerializable types on dotnet core 2.0

### ISSUE THREAD

**Issue by Cisien** [JamesNK/Newtonsoft.Json#1404]
### Source/destination types

```csharp
System.IO.DirectoryInfo
```

### Source/destination JSON
None/serialization fails.

### Expected behavior
Serialization of the DirectoryInfo object to function how it works on .net 4.x

### Actual behavior
```
Message: System.PlatformNotSupportedException : Operation is not supported on this platform.
at System.IO.FileSystemInfo.GetObjectData(SerializationInfo info, StreamingContext context)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeISerializable(JsonWriter writer, ISerializable value, JsonISerializableContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at CSDiscordService.EvalTests.<JsonConvertOfDirectoryInfoObject>d__15.MoveNext() in C:\src\CSDiscord\CSDiscordService.Tests\EvalTests.cs:line 88
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Result Message:	System.PlatformNotSupportedException : Operation is not supported on this platform.
```
Appears to be related to a change made in the .net core implementation to no longer support serializing several types. 
https://github.com/dotnet/corefx/pull/20220

### Steps to reproduce
```
PM> dotnet --info
.NET Command Line Tools (2.0.1-servicing-006924)

Product Information:
 Version:            2.0.1-servicing-006924
 Commit SHA-1 hash:  1ed6be56ca

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16257
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.1-servicing-006924\

Microsoft .NET Core Shared Framework Host
  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

```csharp
var di = Directory.CreateDirectory("C:\\this\\doesnt\\exist");
var json = JsonConvert.SerializeObject(di);
Console.WriteLine(json);
```

### Other Observations ###

`SerializerSettings.Error = (s, e) => e.ErrorContext.Handled = true;` does not handle this exception
setting `SerializerSettings.ContractResolver = new DefaultContractResolver { IgnoreSerializableInterface = true };` does not change this behavior

**Comment by JamesNK** [comment]
Fixed a couple of months ago. Test https://github.com/JamesNK/Newtonsoft.Json/commit/90514188c05bfc5548181b08f807d69eac171071

**Comment by Cisien** [comment]
That test doesnt seem to have anything to do with this issue?

**Comment by JamesNK** [comment]
It shows that the type isn't being serialized using ISerializable

**Comment by CarlosOnline** [comment]
Any status on this issue?  I am also seeing the same problem with dotnet version 2.1.2

**Comment by Cisien** [comment]
Grab the latest pre-release of Newtonsoft.Json
