### ISSUE TITLE
ReadAsDateTimeOffsetUnitedStatesDate [FAIL]

### ISSUE THREAD

**Issue by benaadams** [JamesNK/Newtonsoft.Json#1412]
Run unit tests, region United Kingdom
```
.\Build\runbuild.cmd
```
Error
```
[xUnit.net 00:00:10.5185085]     Newtonsoft.Json.Tests.JsonTextReaderTests.ReadTests.ReadAsDateTimeOffsetUnitedStatesDate [FAIL]
[xUnit.net 00:00:10.5185748]       Newtonsoft.Json.JsonReaderException : Could not convert string to DateTimeOffset: 1/30/2011. Path 'Offset', line 1, position 21.
[xUnit.net 00:00:10.5186103]       Stack Trace:
[xUnit.net 00:00:10.5186510]         C:\GitHub\Newtonsoft.Json\Working\Src\Newtonsoft.Json\JsonReader.cs(904,0): at Newtonsoft.Json.JsonReader.ReadDateTimeOffsetString(String s)
[xUnit.net 00:00:10.5187165]         C:\GitHub\Newtonsoft.Json\Working\Src\Newtonsoft.Json\JsonTextReader.cs(725,0): at Newtonsoft.Json.JsonTextReader.FinishReadQuotedStringValue(ReadType readType)
[xUnit.net 00:00:10.5187769]         C:\GitHub\Newtonsoft.Json\Working\Src\Newtonsoft.Json\JsonTextReader.cs(609,0): at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
[xUnit.net 00:00:10.5188464]         C:\GitHub\Newtonsoft.Json\Working\Src\Newtonsoft.Json.Tests\JsonTextReaderTests\ReadTests.cs(555,0): at Newtonsoft.Json.Tests.JsonTextReaderTests.ReadTests.ReadAsDateTimeOffsetUnitedStatesDate()
Failed   Newtonsoft.Json.Tests.JsonTextReaderTests.ReadTests.ReadAsDateTimeOffsetUnitedStatesDate
Error Message:
 Newtonsoft.Json.JsonReaderException : Could not convert string to DateTimeOffset: 1/30/2011. Path 'Offset', line 1, position 21.
Stack Trace:
   at Newtonsoft.Json.JsonReader.ReadDateTimeOffsetString(String s) in C:\GitHub\Newtonsoft.Json\Working\Src\Newtonsoft.Json\JsonReader.cs:line 904
   at Newtonsoft.Json.JsonTextReader.FinishReadQuotedStringValue(ReadType readType) in C:\GitHub\Newtonsoft.Json\Working\Src\Newtonsoft.Json\JsonTextReader.cs:line 725
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType) in C:\GitHub\Newtonsoft.Json\Working\Src\Newtonsoft.Json\JsonTextReader.cs:line 609
   at Newtonsoft.Json.Tests.JsonTextReaderTests.ReadTests.ReadAsDateTimeOffsetUnitedStatesDate() in C:\GitHub\Newtonsoft.Json\Working\Src\Newtonsoft.Json.Tests\JsonTextReaderTests\ReadTests.cs:line 555
```
And
```
[xUnit.net 00:00:10.1883424]     Newtonsoft.Json.Tests.JsonTextReaderTests.ReadAsyncTests.ReadAsDateTimeOffsetUnitedStatesDateAsync [FAIL]
[xUnit.net 00:00:10.1884518]       Newtonsoft.Json.JsonReaderException : Could not convert string to DateTimeOffset: 1/30/2011. Path 'Offset', line 1, position 21.
[xUnit.net 00:00:10.1885240]       Stack Trace:
[xUnit.net 00:00:10.1885801]         C:\GitHub\Newtonsoft.Json\Working\Src\Newtonsoft.Json\JsonReader.cs(904,0): at Newtonsoft.Json.JsonReader.ReadDateTimeOffsetString(String s)
[xUnit.net 00:00:10.1886689]         C:\GitHub\Newtonsoft.Json\Working\Src\Newtonsoft.Json\JsonTextReader.cs(725,0): at Newtonsoft.Json.JsonTextReader.FinishReadQuotedStringValue(ReadType readType)
[xUnit.net 00:00:10.1887648]         C:\GitHub\Newtonsoft.Json\Working\Src\Newtonsoft.Json\JsonTextReader.Async.cs(1169,0): at Newtonsoft.Json.JsonTextReader.<ReadStringValueAsync>d__37.MoveNext()
[xUnit.net 00:00:10.1888276]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:10.1888619]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:10.1888931]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:10.1889251]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:10.1889657]         C:\GitHub\Newtonsoft.Json\Working\Src\Newtonsoft.Json\JsonTextReader.Async.cs(1691,0): at Newtonsoft.Json.JsonTextReader.<DoReadAsDateTimeOffsetAsync>d__47.MoveNext()
[xUnit.net 00:00:10.1890218]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:10.1890620]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:10.1891142]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:10.1891797]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:10.1892515]         C:\GitHub\Newtonsoft.Json\Working\Src\Newtonsoft.Json.Tests\JsonTextReaderTests\ReadAsyncTests.cs(541,0): at Newtonsoft.Json.Tests.JsonTextReaderTests.ReadAsyncTests.<ReadAsDateTimeOffsetUnitedStatesDateAsync>d__21.MoveNext()
[xUnit.net 00:00:10.1893451]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:10.1894019]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:10.1894544]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:10.1895125]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:10.1895512]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:10.1896001]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:10.1896589]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:10.1897173]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[xUnit.net 00:00:10.1897620]         --- End of stack trace from previous location where exception was thrown ---
[xUnit.net 00:00:10.1898038]            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
[xUnit.net 00:00:10.1898492]            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[xUnit.net 00:00:10.1898922]            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Failed   Newtonsoft.Json.Tests.JsonTextReaderTests.ReadAsyncTests.ReadAsDateTimeOffsetUnitedStatesDateAsync
Error Message:
 Newtonsoft.Json.JsonReaderException : Could not convert string to DateTimeOffset: 1/30/2011. Path 'Offset', line 1, position 21.
Stack Trace:
   at Newtonsoft.Json.JsonReader.ReadDateTimeOffsetString(String s) in C:\GitHub\Newtonsoft.Json\Working\Src\Newtonsoft.Json\JsonReader.cs:line 904
   at Newtonsoft.Json.JsonTextReader.FinishReadQuotedStringValue(ReadType readType) in C:\GitHub\Newtonsoft.Json\Working\Src\Newtonsoft.Json\JsonTextReader.cs:line 725
   at Newtonsoft.Json.JsonTextReader.<ReadStringValueAsync>d__37.MoveNext() in C:\GitHub\Newtonsoft.Json\Working\Src\Newtonsoft.Json\JsonTextReader.Async.cs:line 1169
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Newtonsoft.Json.JsonTextReader.<DoReadAsDateTimeOffsetAsync>d__47.MoveNext() in C:\GitHub\Newtonsoft.Json\Working\Src\Newtonsoft.Json\JsonTextReader.Async.cs:line 1691
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Newtonsoft.Json.Tests.JsonTextReaderTests.ReadAsyncTests.<ReadAsDateTimeOffsetUnitedStatesDateAsync>d__21.MoveNext() in C:\GitHub\Newtonsoft.Json\Working\Src\Newtonsoft.Json.Tests\JsonTextReaderTests\ReadAsyncTests.cs:line 541
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by JamesNK** [comment]
I set the region to UK in Win10 and ran the tests and didn't get any errors.

![image](https://user-images.githubusercontent.com/303201/29993331-632ed288-9008-11e7-9084-675995484a8b.png)

Does "en-US" used in the test rely on English (US) being installed on the computer?
