### ISSUE TITLE
Possible thread-unsafe serialization - DefaultReferenceResolver

### ISSUE THREAD

**Issue by kiziu** [JamesNK/Newtonsoft.Json#1452]
Application I am developing has been throwing for some time intermittent exceptions:
> Newtonsoft.Json.JsonSerializationException: Error writing object reference for '<TYPE>'. Path '$values[34]'. ---> System.ArgumentException: A different value already has the Id '<ID>'.
I tried reproducing in debug sessions, but I couldn't get any results. After that, I started looking at the code based on the stack trace, which lead to method [https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalWriter.cs#L366](JsonSerializerInternalWriter.GetReference). From there, I went to [https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/DefaultReferenceResolver.cs#L69](DefaultReferenceResolver.GetReference). I suspect that _JsonSerializer_ is not thread-safe because of this resolver. Although _JsonSerializerInternalWriter_ is instantiated for each serialization/deserialization process (therefore the reference mappings are also "local"), the resolver is provided by _JsonSerializer_ via method [https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/JsonSerializer.cs#L1150](JsonSerializer.GetReferenceResolver), which means that the resolver is reused between different threads (which could be parallel). Since the **__referenceCount_** field is reused, any access to it should be locked, as two parallel threads might start incrementing and using the same value for reference. Can you please confirm my suspicions and maybe fix this in next release? Thank you!

### Steps to reproduce

Highly unlikely to reproduce, as the referenceCount incrementation must occur at almost the same time on two parallel threads.

**Comment by TylerBrinkley** [comment]
#1393 should fix this issue. If that's not accepted `Interlocked.Increment` should be used.

**Comment by TylerBrinkley** [comment]
@JamesNK this is a real issue due to your use of the post increment operator [here](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Serialization/DefaultReferenceResolver.cs#L65). I'd suggest you should consider accepting #1393 which also corrects this issue. Alternatively you could simply fix this by replacing the post increment operator with a call to `Interlocked.Increment` instead.

**Comment by TylerBrinkley** [comment]
@JamesNK Please consider fixing this concurrency issue. I've laid out the potential fixes, just waiting on you to okay a direction.

**Comment by Terebi42** [comment]
@TylerBrinkley  @JamesNK  My app is hitting this issue during heavy usage in production :(

**Comment by Sergey-Terekhin** [comment]
It's actual for v.11

**Comment by TylerBrinkley** [comment]
@JamesNK Please consider fixing this concurrency issue. I've laid out the potential fixes, just waiting on you to okay a direction.

**Comment by jmrnilsson** [comment]
Yep, this is a thing in highly congested scenarios. Perhaps only in such scenarios.

**Comment by jmrnilsson** [comment]
Me thought ReferanceResolver was the cause of wierd output but turned out to be static variable elsewhere..

**Comment by Sergey-Terekhin** [comment]
I use `ThreadLocal<Newtonsoft.Json.JsonSerializer>` instead of shared instance. It allows to avoid locks and be thread-safe. The cost is instance per thread (not so much I think)

**Comment by apdevelop** [comment]
Had a similar issue (but it's hard to reproduce) with `DefaultContractResolver` and latest (12.0.2) version. The `JsonConvert.SerializeObject` is called inside async method and in random cases  exception is thrown:

    Parameter name: attributeProvider System.ArgumentNullException
    at System.Attribute[] GetAttributes(System.Object, System.Type, Boolean)
    at Newtonsoft.Json.Utilities.ReflectionUtils.GetAttributes(Object attributeProvider, Type attributeType, Boolean inherit)
    at Newtonsoft.Json.Utilities.ReflectionUtils.GetAttributes[T](Object attributeProvider, Boolean inherit)
    at Newtonsoft.Json.Utilities.ReflectionUtils.GetAttribute[T](Object attributeProvider, Boolean inherit)
    at Newtonsoft.Json.Serialization.JsonTypeReflector.GetAttribute[T](Type type)
    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
    at Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(JsonContract contract)
    at Newtonsoft.Json.Serialization.DefaultContractResolver.CreatePrimitiveContract(Type objectType)
    at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
    at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
    at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
    at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
    at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
    at Newtonsoft.Json.JsonConvert.SerializeObject(Object value)

**Comment by stricq** [comment]
Why has this not been fixed yet?  I'm hitting this issue in 12.0.3.  I really can't understand why this issue has been sitting unfixed for 3 YEARS.

**Comment by stricq** [comment]
One year on and still not fixed.

**Comment by sungam3r** [comment]
This is normal for oss.

**Comment by CenturySparkle** [comment]
This is still a major problem.  Why has this not been fixed?  Especially when the fix is so drop dead simple?  I see version after version after version released for this software, and that's great.  But why such a simple fix keeps getting ignored is beyond my understanding.

**Comment by sungam3r** [comment]
This is normal for oss project which is no longer actively developed.

**Comment by CenturySparkle** [comment]
Looks like it is actively being developed to me.  And, the issue has been open for 5 years now.

**Comment by sungam3r** [comment]
https://github.com/JamesNK/Newtonsoft.Json/graphs/contributors 

Over the past few years, trends (commits, open/merged PRs) are obvious.

https://github.com/JamesNK/Newtonsoft.Json/issues/862#issuecomment-1013762922

**Comment by jmrnilsson** [comment]
I did write something on an issue around here somewhere a few year ago. Anyways my issue was actually poor thread safety else were that made Newtonsoft go boom. Check for static variables elsewhere, that could be a clue for some.
