### ISSUE TITLE
11.0.1-beta2: Error serializing nullable decimal

### ISSUE THREAD

**Issue by frankbuckley** [JamesNK/Newtonsoft.Json#1561]
### Source/destination types

```csharp
    public class Data
    {
        public decimal? Value { get; set; }
    }
```

### Expected behavior

Assigned value is serialized.

### Actual behavior

    Newtonsoft.Json.JsonWriterException
      HResult=0x80131500
      Message=Token Float in state Object would result in an invalid JSON object. Path ''.
      Source=Newtonsoft.Json
      StackTrace:
       at Newtonsoft.Json.JsonWriter.AutoComplete(JsonToken tokenBeingWritten)
       at Newtonsoft.Json.JsonTextWriter.WriteValue(Decimal value)
       at Newtonsoft.Json.JsonWriter.WriteValue(Nullable`1 value)
       at Newtonsoft.Json.JsonWriter.WriteValue(JsonWriter writer, PrimitiveTypeCode typeCode, Object value)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
       at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
       at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
       at JsonTest.Program.Main(String[] args) in D:\dsedev\src\temp\JsonTest\JsonTest\Program.cs:line 15

### Steps to reproduce

```csharp
    // <PackageReference Include="Newtonsoft.Json" Version="11.0.1-beta2" />
    public class Program
    {
        static int Main(string[] args)
        {
            var data = new Data()
            {
                Value = 1.1m
            };

            var serialized = JsonConvert.SerializeObject(data);

            Console.WriteLine(serialized);

            Console.ReadLine();

            return 0;
        }
    }

```

**Comment by JamesNK** [comment]
Whoops. Thanks for the simple repo. Fixed - https://github.com/JamesNK/Newtonsoft.Json/commit/e57cb6acea721b46c2dede63702d22f2617c51ee

I'll release a beta3
