### ISSUE TITLE
Bug while Serializing object when ExpandoObject property is on the base class

### ISSUE THREAD

**Issue by brunoss** [JamesNK/Newtonsoft.Json#1593]
### Expected behavior

Serialization should serialize data successfully

### Actual behavior

Null Reference exception while serializing object

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.CreateMethodCall[T](MethodBase method)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.SetExtensionDataDelegates(JsonObjectContract contract, MemberInfo member)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, JsonSerializerSettings settings)
   at Sytel.Mdn.Configuration.ConfigClient.UpdateNodeAux(String tenant, NodeModel node, String path) in D:\sytel\SCC\subversion\10.7_dev\sytel.mdn2\Configuration\ConfigClient.cs:line 262
```

### Steps to reproduce

```csharp
class BaseModel{
    public BaseModel() {
        Extra = new ExpandoObject();
    }
    [JsonExtensionData]
    public ExpandoObject Extra{ get; set; }
}

class SpecificModel : BaseModel{
    public int Specific{get;set;}
}

BaseModel CreateModel(){
    var model = new SpecificModel();
    var extra = model.Extra as IDictionary<string, object>;
    extra["A"] = 1;
    model.Specific = 2;
    return model;
}

void Main()
{
    JsonConvert.SerializeObject(CreateModel()).Dump();
}
```

**Comment by JamesNK** [comment]
Thanks for the repo. Fixed here https://github.com/JamesNK/Newtonsoft.Json/commit/d6c3794556bca750390556567afe8dea969836bb
