### ISSUE TITLE
Misleading ArgumentOutOfRangeException when Parsing a RegexString without '/'-enclosure

### ISSUE THREAD

**Issue by mmodrow** [JamesNK/Newtonsoft.Json#1601]
Appearently a JSON value that is supposed to get parsed to `System.Text.RegularExpressions.Regex` has to be formatted as `"/someregexpattern/"`.

That is fine. I would prefer to parse values like `"someregexpattern"` to be valid and have no options, but if that is not desired it's fine.

The problem arises here:
https://github.com/JamesNK/Newtonsoft.Json/blob/92d170a0783bc962f52faf02acfcecbe21d3b683/Src/Newtonsoft.Json/Converters/RegexConverter.cs#L149-L154

I prepared a Gist with an example [here](https://gist.github.com/MarcAMo/cba84f0637c0f3bd92803b1c7cd82ed5)

Or as follows:
```CS
using System.Text.RegularExpressions;
using Newtonsoft.Json;
					
public class Program
{
	public static void Main()
	{
		ClassWithRegexAttribute objectWithRegexAttribute = 
      JsonConvert.DeserializeObject<ClassWithRegexAttribute>(
      "{\"RegexAttribute\": \"committing-some-shitty-code-on-my-colleagues\"}");
	}
}

public class ClassWithRegexAttribute 
{
	public Regex RegexAttribute { get; set; }
}
```

Creates this trace:
```
System.ArgumentOutOfRangeException : Length cannot be less than zero.
Parameter name: length
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Newtonsoft.Json.Converters.RegexConverter.ReadRegexString(JsonReader reader)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
```

The problem is, that in some patterns no `/` is present. If no `/` occurs within the pattern and it is not enclosed in them, `patternOptionDelimiterIndex` is -1, resulting in `regexText.Substring(1, -2);`.

This throws the mentioned `ArgumentOutOfRangeException`. I think it would be better to throw a proper exception here that clearly indicates, that the `/` are missing.

As said before I'd prefer to accept the string nontheless, but an Exception would be better than it is now for sure.

I would like to propose something along the lines of:
```CS
 private object ReadRegexString(JsonReader reader)
        {
            string regexText = (string)reader.Value;
            int patternOptionDelimiterIndex = regexText.LastIndexOf('/');

            if (patternOptionDelimiterIndex < 0)
            {
                throw JsonSerializationException.Create(reader, "No pattern option delimiter '/' found.");
            }
```

**Comment by JamesNK** [comment]
Thinks for the detailed bug report. I've improved the error message https://github.com/JamesNK/Newtonsoft.Json/commit/41c3a71e6237004b9a65d4172ba90242bdfe0718

**Comment by mmodrow** [comment]
Thank you for handling this.
