### ISSUE TITLE
Odd serialization issue re: constructors

### ISSUE THREAD

**Issue by eklein23** [JamesNK/Newtonsoft.Json#1608]
We ran into a weird issue related to parameter naming in constructors.  When deserializing an object into a class, the JSON.NET looks for constructors to use, starting with a default constructor.  If the best matching constructor happens to have an argument whose name *resembles* one of the class properties, it will deserialize that property using the type of the constructor argument.  That's fine if the constructor argument and the class property do refer to the same entity, but it's a problem if they don't.

Attached is a simple example showing the issue.  Note that the Thing class has an object property "User" but the constructor has a string parameter "user".  They have a similar name but don't refer to the same entity.  When this code runs, it generates a JsonReaderException on the last line, because the library incorrectly tries to deserialize the user value as a string rather than an object.  Renaming the Thing constructor parameter to something else (like "userName") makes the error go away and allows the class to deserialize correctly.

This is not a major issue, as the workaround is pretty painless.  It did take us some time to figure out, so maybe it's worth sharing.

```
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace ConsoleApp1
{
    class Person
    {
        public string Name { get; set; }

        public Person (string name)
        {
            Name = name;
        }
    }

    class Thing
    {
        public Person User { get; set; }

        public Thing (string user)
        {
            User = new Person(user);
        }
    }

    class Program
    {
        static void Main (string[] args)
        {
            Thing foo = new Thing("test");
            JObject obj = JObject.FromObject(foo);
            Thing foo2 = obj.ToObject<Thing>();
        }
    }
}
```

**Comment by mtwoodbury** [comment]
Happened to me as well in Newtonsoft.Json V 12.0.2 .Net Core 2.2

I have the call stack from the exception is it would help. Glad I checked the "similar issues" link before posting.

Great tool. I wanted to pass on this issue I found by chance with a class hierarchy name collision.
In the base class we have a property `long? Sequence`. In the derived class we introduce a different sequence named  `long sourceSequence` which is setup in the constructor.

In the original derived class constructor, the first argument was named `long sequence`. 
When deserializing as the stack shows, I got the an error about the `Sequence element` which is a nullable long, and normally works fine with null values. 

I corrected the issue by renaming the constructor argument declaration from `sequence` to `sourceSequence`. I did not anticipate the placeholder argument conflicting with the class property.

```
Error converting value {null} to type 'System.Int64'. Path 'Sequence', line 1, position 230.
```
Again, thank you for such a great tool.

**Comment by mtwoodbury** [comment]
Before I loose the details. Adding them here.
### Destination types

```csharp
// Derived Class
namespace Gateway.Securities.Events
{
    using System;

    public class SequenceMaintained : Event
    {
        public SequenceMaintained(
            long sourceSequence,
            Guid securityId,
            string symbol)
        {
            SourceSequence = sourceSequence;
            SecurityId = securityId;
            Symbol = symbol;
        }

        public long SourceSequence { get; }
        public Guid SecurityId { get; }
        public string Symbol { get; }
    }
}

// Base Class
namespace Gateway.Securities.Events
{
    using System;
    using Foundation.Messaging;

    public abstract class Event : IEvent
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        public Guid CorrelationId { get; set; }
        public Guid CausationId { get; set; }
        public string Token { get; set; }
        public string OriginatingToken { get; set; }
        public long? Sequence { get; set; }
        public long? PreviousSequence { get; set; }

        public void SetSource(ICorrelatedMessage source)
        {
            CorrelationId = source.CorrelationId;
            CausationId = source.Id;
        }
    }
}


```

### Source JSON
{
    "MessageSequence": 468130,
    "Id": "b1a83749-21c1-423a-9944-d8112a153555",
    "CorrelationId": "00000000-0000-0000-0000-000000000000",
    "CausationId": "00000000-0000-0000-0000-000000000000",
    "Token": null,
    "OriginatingToken": null,
    "Sequence": null,
    "PreviousSequence": null
}

### Expected behavior

The SequenceMaintained class construction

### Actual behavior
Exception
Error converting value {null} to type 'System.Int64'. Path 'Sequence', line 1, position 230.
(The position may not match the json above, as I ran many tests.)

### Steps to reproduce
We pull a series of bytes from a database, and reconstitute the json. That is then deserialized into the provided class
Here is the call stack which shows you everything. If you need more let me know.

```csharp

Error converting value {null} to type 'System.Int64'. Path 'Sequence', line 1, position 230.

   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 989
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 2203
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 1943
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 476
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 167
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:line 907
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer) in /_/Src/Newtonsoft.Json/Linq/JToken.cs:line 2070
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer) in /_/Src/Newtonsoft.Json/Linq/JToken.cs:line 2057
   at Gateway.Securities.Foundation.SerializationRegistryExtensions.<>c__2`1.<RegisterDefaults>b__2_1(JObject json) in C:\dev\Gateway.Securities\src\Securities\Foundation\SerializationRegistryExtensions.cs:line 34
   at Gateway.Securities.Foundation.SerializationRegistry.<>c__DisplayClass5_0.<Register>g__Deserialize|0(RecordedEvent re) in C:\dev\Gateway.Securities\src\Securities\Foundation\SerializationRegistry.cs:line 43
   at Gateway.Securities.Foundation.MessageDeserializer.Deserialize(RecordedEvent re) in C:\dev\Gateway.Securities\src\Securities\Foundation\MessageDeserializer.cs:line 24
   at Gateway.Securities.Foundation.EventStoreRepository.Load[T]() in C:\dev\Gateway.Securities\src\Securities\Foundation\EventStoreRepository.cs:line 203
   at Gateway.Securities.Foundation.EventStoreRepository.TryLoad[T]() in C:\dev\Gateway.Securities\src\Securities\Foundation\EventStoreRepository.cs:line 146
```

**Comment by TylerBrinkley** [comment]
I'm getting no error in this repro.

```c#
void Main()
{
    var value = JsonConvert.DeserializeObject<SequenceMaintained>(@"{
""MessageSequence"": 468130,
""Id"": ""b1a83749-21c1-423a-9944-d8112a153555"",
""CorrelationId"": ""00000000-0000-0000-0000-000000000000"",
""CausationId"": ""00000000-0000-0000-0000-000000000000"",
""Token"": null,
""OriginatingToken"": null,
""Sequence"": null,
""PreviousSequence"": null
}");
}

// Define other methods and classes here
public class SequenceMaintained : Event
{
    public SequenceMaintained(
        long sourceSequence,
        Guid securityId,
        string symbol)
    {
        SourceSequence = sourceSequence;
        SecurityId = securityId;
        Symbol = symbol;
    }

    public long SourceSequence { get; }
    public Guid SecurityId { get; }
    public string Symbol { get; }
}

public abstract class Event
{
    public Guid Id { get; set; } = Guid.NewGuid();
    public Guid CorrelationId { get; set; }
    public Guid CausationId { get; set; }
    public string Token { get; set; }
    public string OriginatingToken { get; set; }
    public long? Sequence { get; set; }
    public long? PreviousSequence { get; set; }
}
```

**Comment by mtwoodbury** [comment]
Try changing the sequence maintained to this. I posted the corrected code. Sorry.
```
public class SequenceMaintained : Event
{
    public SequenceMaintained(
        long sequence,
        Guid securityId,
        string symbol)
    {
        SourceSequence = sequence;
        SecurityId = securityId;
        Symbol = symbol;
    }

    public long SourceSequence { get; }
    public Guid SecurityId { get; }
    public string Symbol { get; }
}
```

**Comment by TylerBrinkley** [comment]
That would be the issue, Json.NET makes the reasonable assumption that a parameter with a name that matches a json property of the same name should be injected into the constructor. I find this behavior extremely useful. I'd suggest you rename your `sequence` parameter to `sourceSequence`.

While it wouldn't catch your case here, ideally a roslyn analyzer could be made that uses the same constructor resolution logic as Json.NET and it could warn you when a constructor parameter name doesn't match a class's property name. I've been bit before when I had a typo in the parameter name so that the value wasn't being injected into the constructor.

**Comment by mtwoodbury** [comment]
Thanks for the quick reply and explanation.  I'll make sure people are aware.
