### ISSUE TITLE
JsonSerializationException after update to v11

### ISSUE THREAD

**Issue by PawelGerr** [JamesNK/Newtonsoft.Json#1620]
After update to v11 an exception is throw if the value is a mock (https://www.nuget.org/packages/moq/).

```csharp
var mock = new Mock<IFoo>();
IFoo foo = mock.Object;

var settings = new JsonSerializerSettings() { Converters = { new FooConverter() } };
var json = JsonConvert.SerializeObject(foo, settings);
```

The reason lies in [ReflectionUtils.cs](https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Utilities/ReflectionUtils.cs).GetProperties() returning 2 properties with the same name instead of 1.
This method is now being called with `BindingFlags`: `Instance | Static | Public | NonPublic`. 
In v10 the `BindingFlags` are `Instance | Public `.

The method `GetFieldsAndProperties` calling `GetProperties` has some special handling to filter out "duplicates" but not in this case.

```csharp
// this is a bit hacky
// if the hiding property is hiding a base property and it is virtual
// then this ensures the derived property gets used
if (resolvedMembers.Count == 0)
{
          resolvedMembers.Add(memberInfo);
}
else if (!IsOverridenGenericMember(memberInfo, bindingAttr) || memberInfo.Name == "Item")
{
          resolvedMembers.Add(memberInfo);
}
```

### Expected behavior
Custom JsonConverter is being used for serialization of `IFoo`.

### Actual behavior
An exception is thrown in v11

### Steps to reproduce
Repro: https://github.com/PawelGerr/Newtonsoft.Json.v11.Repro

* The project `JsonRepro10` serializes the object using custom converter
* `JsonRepro11` throw an exception

```csharp
Unhandled Exception: Newtonsoft.Json.JsonSerializationException: A member with the name 'Mock' already exists on 'Castle.Proxies.IFooProxy'. Use the JsonPropertyAttribute to specify another name.
   at Newtonsoft.Json.Serialization.JsonPropertyCollection.AddProperty(JsonProperty property)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties(Type type, MemberSerialization memberSerialization)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at JsonRepro11.Program.Main(String[] args) in S:\Sources\PG\Repos\Newtonsoft.Json.v11.Repro\JsonRepro11\Program.cs:line 15

```

**Comment by JamesNK** [comment]
Thanks for the detailed description and repo. Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/f2b6ea4966f2c99a38e07bb3b0d93f19db1da77b

Stick with 10.0.3 for now. A new version of 11 will come out in a week or two.
