### ISSUE TITLE
classes deriving from System.Exception do not serialize/deserialize properly

### ISSUE THREAD

**Issue by jonreis** [JamesNK/Newtonsoft.Json#1622]
#In Newtonsoft.Json v11.0.1, without the [Serializable] attribute on MyExceptionClass, the following test fails. Adding it succeeds.

If I run this test with Newtonsoft.Json v10.0.3 it passes without the [Serializable]

    //[Serializable]
	  public class MyExceptionClass : Exception
	  {
	  }

    [Test]
    public void SerializeException()
    {
      Exception exception;
      try
      {
        throw new MyExceptionClass();
      }
      catch (Exception ex)
      {
        exception = ex;
      }
      string sex = JsonConvert.SerializeObject(exception);
      var dex = JsonConvert.DeserializeObject<Exception>(sex);
      Assert.AreEqual(dex.ToString(), exception.ToString());
    }

The error generated is:

System.Runtime.Serialization.SerializationException : Member 'ClassName' was not found.
   at System.Runtime.Serialization.SerializationInfo.GetElement(String name, Type& foundType)
   at System.Runtime.Serialization.SerializationInfo.GetString(String name)
   at System.Exception..ctor(SerializationInfo info, StreamingContext context)
   at Void .ctor(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)(Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializable(JsonReader reader, JsonISerializableContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Connexion.Core.Internal.SerializationEx.Deserialize[T](String value) in D:\Development\Bitbucket\connexion\Connexion.Core\Internal\Json\SerializationEx.cs:line 125
   at Connexion.Share.Test.SerializationTests.SerializeException() in D:\Development\Bitbucket\connexion\Connexion.Share.Test\SerializationTests.cs:line 324

**Comment by JamesNK** [comment]
That's expected behavior. Json.NET previous wasn't serializing `ISerializable` types correctly. The `SerializableAttribute` is required.

See here for more info https://github.com/dotnet/corefx/issues/23415

**Comment by jonreis** [comment]
Hi JamesNK thanks for the response. 

Often exceptions are thrown from 3rd party library code that cannot be changed. Additionally,  it is very rare that for someone deriving from Exception to remember to decorate the class with SerializableAttribute.

Given that it worked fine in Newtonsoft.Json v10.0.3, I would suspect that it will break a lot of users that upgrade and have been passing serialized exceptions around.

Would you recommend me creating a custom Converter to handle the serialization of exception explicitly? Or, how would you handle this?

**Comment by luigidallavalle** [comment]
Hi all, as for today, is there a supported method to serialize / deserialize exceptions?
@jonreis how did you solve your issue?

Thanks

**Comment by jonreis** [comment]
@luigidallavalle sorry about the late response. We never found a solution so we went through all of our Exception derived classes and added  [Serializable] to them.

**Comment by alexhiggins732** [comment]
What happens if you don't have control over the class? For example, .Net Core 2.2 app new `System.Exception` serializes as:

```csharp
{
  "Message": "Exception of type 'System.Exception' was thrown.",
  "Data": {},
  "InnerException": null,
  "TargetSite": null,
  "StackTrace": null,
  "HelpLink": null,
  "Source": null,
  "HResult": -2146233088
}
```

Yet my WebAPI (Net 4.72) using throws the error `System.Runtime.Serialization.SerializationException: 'Member 'ClassName' was not found.'`.

Serialize a new `System.Exception` there produces:

```csharp
{
  "ClassName": "System.Exception",
  "Message": null,
  "Data": null,
  "InnerException": null,
  "HelpURL": null,
  "StackTraceString": null,
  "RemoteStackTraceString": null,
  "RemoteStackIndex": 0,
  "ExceptionMethod": null,
  "HResult": -2146233088,
  "Source": null,
  "WatsonBuckets": null
}
```
4.7 has `System.Exception` defined in `Assembly = {mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089}` where core defines in `Assembly = {System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e}`

There is no end user control over this.

**Comment by TCGV** [comment]
Bellow is a quick workaround for those who can't  place SerializableAttribute on exceptions (ex: Third Party):

- [TCGV/ExceptionSerializer.cs](https://gist.github.com/TCGV/836755af10fdf17b78a323ac23fc41c0)

Simply replace calls to `JsonConvert.SerializeObject(exception)` with `ExceptionSerializer.Serialize(exception)` for producing a JSON string containing all exception's public instance properties.

The output is slightly different from Newtonsoft.Json v10 behavior, but you can easily fiddle with it to achieve what you need.

**Comment by Melchy** [comment]
Another solution is to use new .net core serializer from system.text.json.

**Comment by maxiar** [comment]
Hi! Please help me! 
How to write custom "exception" serialization to deserialize only the common properties between net472 and dot net core exception types when a "error" property is found inside the third-party component.  
May be I need to use the @TCGV trick to write a custom serializacion to my "Error" Property....

**Comment by alexhiggins732** [comment]
> 
> 
> Another solution is to use new .net core serializer from system.text.json.

Does this handle the different layout in NetFX exceptions properly? Not sure how it could.
