### ISSUE TITLE
IndexOutOfRangeException in PropertyNameTable.Get()

### ISSUE THREAD

**Issue by dco123** [JamesNK/Newtonsoft.Json#1753]
I'm seeing an intermittent issue where an IndexOutOfRangeException is thrown from PropertyNameTable.Get(), using 11.0.2. I have many processes loading and deserializing the same set of files, and within a process the same JsonSerializer is deserializing these files in parallel. Most of them are successful but occasionally one or two of them fail with this error.

I suspect it might be a race condition in PropertyNameTable but not sure about that. I reproduced the issue by repeatedly running an app that deserialises files in parallel using the same serializer (though it can take thousands of iterations before I see it), but I can't provide the json / code as it's sensitive. Hopefully the stack below might give some clues.

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Newtonsoft.Json.Utilities.PropertyNameTable.Get(Char[] key, Int32 start, Int32 length)
   at Newtonsoft.Json.JsonTextReader.ParseProperty()
   at Newtonsoft.Json.JsonTextReader.ParseObject()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
```

**Comment by dco123** [comment]
Think i've found the issue. This for loop initializer in DefaultJsonNameTable.Get():
```
Entry entry = _entries[hashCode & _mask]
```
.. is compiled into this IL:

    IL_0064: ldarg.0      // this
    IL_0065: ldfld        class Newtonsoft.Json.DefaultJsonNameTable/Entry[] Newtonsoft.Json.DefaultJsonNameTable::_entries
    IL_006a: ldloc.0      // hashCode
    IL_006b: ldarg.0      // this
    IL_006c: ldfld        int32 Newtonsoft.Json.DefaultJsonNameTable::_mask
    IL_0071: and          
    IL_0072: ldelem.ref   
    IL_0073: stloc.s      entry

The issue is that the value of _entries is pushed onto the stack before 'hashCode & _mask' is evaluated.  Because there's only locking around the Add and not the Get (presumably for performance reasons), this means that if an Add and a Get are running in parallel then the _mask value can get updated in the Grow (during the Add) after the _entries value has been pushed onto the stack in the Get. Then the Get method's thread will evaluate the array index using the updated mask, which is no longer valid for the _entries array instance that was previously pushed onto the stack.

If avoiding locking in the Get is required then a simple fix would be to make sure the index is evaluated before accessing the _entries value:
```
var index = hashCode & _mask;
var entries = _entries;

for (Entry entry = entries[index]; entry != null; entry = entry.Next)
{
  if (entry.HashCode == hashCode && TextEquals(entry.Value, key, start, length))
  {
    return entry.Value;
  }
}
```
This way the the index is guaranteed to be in the range of the _entries array, since it can only grow. It's still possible that the entries array won't be in sync with the hashcode if Grow is called between these two lines, but I think the worst effect of that will be that there might be a false cache miss, but that's probably an acceptable compromise.

**Comment by dco123** [comment]
Confirmed I can't reproduce the issue after making this change so have opened a pull request
https://github.com/JamesNK/Newtonsoft.Json/pull/1756
