### ISSUE TITLE
Error: newtonsoft.json library it referenced did not contain a reference to monotouch.droid

### ISSUE THREAD

**Issue by mhdmaktabi** [JamesNK/Newtonsoft.Json#1771]
Xamarin project made a .net standard(1.4) shared project and tried referencing this library from it. I tried making a build which said that the newtonsoft.json library it referenced did not contain a reference to monotouch.droid.

Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, ....'. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'Newtonsoft.Json.dll'
at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
at Xamarin.Android.Tasks.ResolveAssemblies.AddAssemblyReferences(DirectoryAssemblyResolver resolver, ICollection`1 assemblies, AssemblyDefinition assembly, Boolean topLevel)
at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver) SmartHotel.Clients.Android

**Comment by JamesNK** [comment]
Please raise Android Xamarin issues at https://github.com/xamarin/xamarin-android
