### ISSUE TITLE
Failed to deserialize object previously serialized with TypeNameHandling.Auto

### ISSUE THREAD

**Issue by botondbotos** [JamesNK/Newtonsoft.Json#1791]
### Source/destination types

```csharp
public class Dto
{
    public IEnumerable<string> Items { get; set; }
}
```

### Source/destination JSON

```javascript
{
  "Items": {
    "$type": "System.Linq.Enumerable+WhereSelectEnumerableIterator`2[[System.Int32, mscorlib],[System.String, mscorlib]], System.Core",
    "$values": [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10"
    ]
  }
}
```

### Expected behavior

Deserialization of JSON string resulting from serialization with the same settings should succeed.

### Actual behavior
The following exception is thrown:
```csharp
Newtonsoft.Json.JsonSerializationException
  HResult=0x80131500
  Message=Cannot create and populate list type System.Linq.Enumerable+WhereSelectEnumerableIterator`2[System.Int32,System.String]. Path 'Items.$values', line 4, position 16.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewList(JsonReader reader, JsonArrayContract contract, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at JsonSerialization.Program.Main(String[] args)
```

### Steps to reproduce

```csharp
var dto = new Dto
{
    Items = Enumerable.Range(1, 10).Select(_ => _.ToString())
};

var jsonSerializerSettings = new JsonSerializerSettings
{
    TypeNameHandling = TypeNameHandling.Auto
};

var serialized = JsonConvert.SerializeObject(dto, jsonSerializerSettings);

var deserialized = JsonConvert.DeserializeObject<Dto>(serialized, jsonSerializerSettings);
```

**Comment by JamesNK** [comment]
You can't deserialize back into an enumerator. That's not what an enumerator is.

This will work:

```
var dto = new Dto
{
    Items = Enumerable.Range(1, 10).Select(_ => _.ToString()).ToList()
};
```

**Comment by botondbotos** [comment]
Why does it work with TypeNameHandling.None?

**Comment by SomeDevFromSociabble** [comment]
Hello,
So I feel not including $type for IEnumerables would work, would it be possible to show a quick code on how to do that ?
The following code is okay for serialization but deserialization goes into a StackOverflow
```
public class NoTypeNameEnumerableConverter : JsonConverter
{
	public override bool CanConvert(Type objectType)
	{
		return typeof(IEnumerable).IsAssignableFrom(objectType) && objectType != typeof(string);
	}

	public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
	{
		writer.WriteStartArray();
		foreach (var item in (IEnumerable)value)
		{
			// This reuses the serializer (with TypeNameHandling.Auto) on each item.
			serializer.Serialize(writer, item);
		}
		writer.WriteEndArray();
	}

	public override object ReadJson(
		JsonReader reader, 
		Type objectType, 
		object existingValue, 
		JsonSerializer serializer)
	{
		// Let default deserialization handle it — can improve if needed.
		return serializer.Deserialize(reader, objectType);
	}
}
```
