### ISSUE TITLE
Exception: Could not load type 'System.Runtime.Serialization.SerializationBinder'

### ISSUE THREAD

**Issue by liesauer** [JamesNK/Newtonsoft.Json#1803]
i am working on netcore 2.0 console project, and i use a package `EdjCase.JsonRpc` which referenced `Newtonsoft.Json`, and i got an exception which is thrown by `Newtonsoft.Json`.
```
发生异常: CLR/System.AggregateException
Exception thrown: 'System.AggregateException' in System.Private.CoreLib.dll: 'One or more errors occurred.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.TypeLoadException : Could not load type 'System.Runtime.Serialization.SerializationBinder' from assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at Newtonsoft.Json.JsonSerializer..ctor()
   at Newtonsoft.Json.JsonSerializer.Create(JsonSerializerSettings settings)
   at EdjCase.JsonRpc.Client.DefaultRequestJsonSerializer.SerializeValue(Object value, JsonTextWriter jsonWriter)
   at EdjCase.JsonRpc.Client.DefaultRequestJsonSerializer.SerializeRequest(RpcRequest request, JsonTextWriter jsonWriter)
   at EdjCase.JsonRpc.Client.DefaultRequestJsonSerializer.SerializeInternal(IEnumerable`1 requests, Boolean isBulkRequest)
   at EdjCase.JsonRpc.Client.RpcClient.<SendAsync>d__20.MoveNext()
```

**Comment by liesauer** [comment]
it is nothing about `Newtonsoft.Json`.
