### ISSUE TITLE
JsonConvert re-uses instances to deserialize

### ISSUE THREAD

**Issue by andre-ss6** [JamesNK/Newtonsoft.Json#1811]
Our Asp.Net Core app was acting weirdly in apparently random occasions. After a lot of headache, I eventually managed to find the problem by logging the stack trace in _a lot_ of places: the lib was changing the id of some hardcoded static properties we use here.

I'm sorry for not having a reproducible sample just yet, but I'll work on it and I'll update this post when I'm done.

Anyway, the problem went like this. We have a class with some static instances of it inside itself:

```csharp
public class Status 
{
    public static Status Open => new Status { Id = 1 };
    public static Status Closed => new Status { Id = 2 };

    public int Id { get; set; }
}
```

And we serialize those static instances in a lot of places, and de-serialize to that type as well. For example, we have a generate report method that does things like this:

```csharp
notification.Status = Status.Open;
JsonConvert.SerializeObject(notification);
//...
JsonConvert.DeserializeObject<Notification>(someString);
```

What we found is that in that fourth line (calling Deserialize), the lib would try to change the ID of those static instances. I _would_ think that every time Deserialize is called, a new instance of `T` is created. However, that doesn't seem to be the case. 

In order to make sure the deserializer was really using the static instance, I've put some instrumentation and logging on the class. Here is the real class code:

```csharp

using Newtonsoft.Json;
using Serilog;
using System;
using System.Collections.Generic;
using System.Text;

namespace Company.Product.Entities
{
    public class NotificationStatus
    {
        // this is zero for every instance of this class except for the three static ones
        [JsonIgnore]
        private readonly int staticId;

        public static ILogger Logger { get; set; }

        private static NotificationStatus _pending = new NotificationStatus(1, "Pending", 1);
        private static NotificationStatus _approved = new NotificationStatus(2, "Approved", 2);
        private static NotificationStatus _refused = new NotificationStatus(3, "Refused", 3);

        private static bool errorLogged = false;

        public static NotificationStatus PENDING
        {
            get
            {
                if (!errorLogged && (_pending.ID != 1 || _pending.Name != "Pending"))
                {
                    Logger.Error("PENDING was altered to {@pending}. Stack trace: {@stack}", _pending, Environment.StackTrace);
                    errorLogged = true;
                }

                return _pending;
            }
        }

        public static NotificationStatus APPROVED
        {
            get
            {
                if (!errorLogged && (_approved.ID != 2 || _approved.Name != "Approved"))
                {
                    Logger.Error("APPROVED was altered to {@approved}. Stack trace: {@stack}", _pending, Environment.StackTrace);
                    errorLogged = true;
                }

                return _approved;
            }
        }

        public static NotificationStatus REFUSED
        {
            get
            {
                if (!errorLogged && (_refused.ID != 3 || _refused.Name != "Refused"))
                {
                    Logger.Error("REFUSED was altered to {@refused}. Stack trace: {@stack}", _pending, Environment.StackTrace);
                    errorLogged = true;
                }

                return _refused;
            }
        }

        private int _id;
        public int ID
        {
            get => _id;
            set
            {
                if (_id != value && staticId != 0)
                    Logger.Error($"Tried to change the NotificationStatus' value from {_id} to {value}. Static Id: {staticId}. Stack trace: {Environment.StackTrace}");
            }

        }

        private string _name;
        public string Name
        {
            get => _name;
            set
            {
                if (_name != value && staticId != 0)
                    Logger.Error($"Tried to change the NotificationStatus' value from {_name} to {value}. Static Id: {staticId}. Stack trace: {Environment.StackTrace}");
            }
        }

        private NotificationStatus(int id, string name, int staticId = 0)
        {
            this.staticId = staticId;
            _id = id;
            _name = name;
        }

        public static explicit operator NotificationStatus(int i)
        {
            switch (i)
            {
                case 1:
                    return PENDING;
                case 2:
                    return APPROVED;
                case 3:
                    return REFUSED;
                default:
                    throw new InvalidCastException();
            }
        }

    }
}
```

This is what I found on our logs:

```
{"@t":"2018-08-29T11:39:31.6361247Z","@m":"Tried to change the NotificationStatus' value from 1 to 2. Static Id: 1. 
Stack trace:    
at System.Environment.get_StackTrace()
at Company.Product.Entidades.NotificacaoStatus.set_ID(Int32 value) in [redacted]\\NotificacaoStatus.cs:line 70 
at Newtonsoft.Json.Serialization.ExpressionValueProvider.SetValue(Object target, Object value)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)   
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)  
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)   
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
at Company.Product.Web.Controllers.OrdemServicoController.Exportar(Int32[] ordemIds) in [redacted]\\OrdemServicoController.cs:line 117
at lambda_method(Closure , Object , Object[] )
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAwaitedAsync>d__11.MoveNext()
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAwaitedAsync()
at Microsoft.AspNetCore.Mvc.Controller.<OnActionExecutionAsync>d__27.MoveNext()
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.AspNetCore.Mvc.Controller.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter.<OnActionExecutionAsync>d__4.MoveNext()
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionFilter.OnActionExecutionAsync(ActionExecutingContext context, ActionExecutionDelegate next)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.<Invoke>d__4.MoveNext()
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.StaticFiles.DefaultFilesMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.<Invoke>d__3.MoveNext()
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
at Company.Product.Web.Middlewares.SerilogMiddleware.<Invoke>d__5.MoveNext() in [redacted]\\Middlewares\\SerilogMiddleware.cs:line 66
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
at Company.Product.Web.Middlewares.SerilogMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.<Invoke>d__11.MoveNext()
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.AspNetCore.Server.IISIntegration.IISMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
at Microsoft.AspNetCore.Hosting.Internal.HostingApplication.ProcessRequestAsync(Context context)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.<ProcessRequestsAsync>d__2.MoveNext()
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.LoggingThreadPool.<RunAction>b__3_0(Object o)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadPoolWorkQueue.Dispatch()","@i":"e3e3239a","@l":"Error","ActionId":"4ec1eeb0-cf09-403a-8f30-df9d680a5927","ActionName":"Company.Product.Web.Controllers.OrdemServicoController.Exportar (Company.Product.Web)","RequestId":"0HLGD8D7B8ICS:0000002D","RequestPath":"/OrdemServico/Exportar"}
```

And the same thing for the Name property.

(Note that I've translated those classes' names and things, so pardon me if you find some inconsistencies on the logs)

As you can see - unless I'm missing something - there is no way this could happen unless the deserializer is re-using instances. 

Is this a known thing? Does the deserializer somehow caches instances and just change its properties instead of `new`ing them up?

**Comment by JamesNK** [comment]
>  I would think that every time Deserialize is called, a new instance of T is created.

Use ObjectCreationHandling.Replace
