### ISSUE TITLE
Identity operator not supported

### ISSUE THREAD

**Issue by WillSullivan** [JamesNK/Newtonsoft.Json#1835]
While, as best as I can tell (and that's only by testing it in the online evaluator at jsonpath.com), it should be possible to use the identity operator (===) in a JPath query. This doesn't appear to be supported.

Using their example, 

```javascript
{
  "firstName": "John",
  "lastName" : "doe",
  "age"      : 26,
  "address"  : {
    "streetAddress": "naist street",
    "city"         : "Nara",
    "postalCode"   : "630-0192"
  },
  "phoneNumbers": [
    {
      "type"  : "iPhone",
      "number": "0123-4567-8888"
    },
    {
      "type"  : "home",
      "number": "0123-4567-8910"
    }
  ]
}
```

The JPath

```javascript
$.phoneNumbers[?(@.type==='home')].number
```
returns the expected result

```javascript
[
  "0123-4567-8910"
]
```
However, when executing the following

```csharp
    var sampled = JObject.Parse(sample);
    var results2 = sampled.SelectTokens("$.phoneNumbers[?(@.type==='home')].number");```
```
throws a JsonException

```
Newtonsoft.Json.JsonException: Unexpected character while parsing path query: =
   at Newtonsoft.Json.Linq.JsonPath.JPath.ParseSide()
   at Newtonsoft.Json.Linq.JsonPath.JPath.ParseExpression()
   at Newtonsoft.Json.Linq.JsonPath.JPath.ParseQuery(Char indexerCloseChar, Boolean scan)
   at Newtonsoft.Json.Linq.JsonPath.JPath.ParseIndexer(Char indexerOpenChar, Boolean scan)
   at Newtonsoft.Json.Linq.JsonPath.JPath.ParsePath(List`1 filters, Int32 currentPartStartIndex, Boolean query)
   at Newtonsoft.Json.Linq.JsonPath.JPath.ParseMain()
   at Newtonsoft.Json.Linq.JsonPath.JPath..ctor(String expression)
   at Newtonsoft.Json.Linq.JToken.SelectTokens(String path)
   at GetDemCredsYo.Program.Main(String[] args)
```
Using `==` works as expected, but it can result in unforced errors when those familiar with javascript and the JPath syntax stumble into this.

**Comment by WillSullivan** [comment]
There appears to be other issues with equality.  Testing on http://jsonpath.com/, given the following json


```javascript
{
	"Values": [{
		"Coercible": 1,
		"Name": "Number"
	}, {
		"Coercible": "1",
		"Name": "String"
	}]
}
```

And the following tests, the results are as listed after each test:

```javascript
Values[?(@.Coercible == '1')].Name
```
JSONPath result: 
```javascript
[
  "Number",
  "String"
]
```
SelectTokens result: 
```csharp
{ "String" }
```
----------------
```javascript
Values[?(@.Coercible != '1')].Name
```
JSONPath result: no matches.
SelectTokens result:
```csharp
{ "Number" }
```
----------------
There's definitely different behavior exhibited by SelectTokens, as it appears there isn't coercion going on at all, even though the method used for the equals op is called EqualsWithStringCoercion and appears to attempt coercion on the values being compared.

I've got a pull request inbound that includes support for ```===``` and ```!==``` operators in JPath which matches the expected behavior for these operators as tested on JSONPath:

```javascript
Values[?(@.Coercible === 1)].Name
```
JSONPath result: 
```javascript
[
  "Number"
]
```
----------------
```javascript
Values[?(@.Coercible !== 1)].Name
```
JSONPath result: 
```javascript
[
  "String"
]
```
----------------
```javascript
Values[?(@.Coercible === '1')].Name
```
JSONPath result: 
```javascript
[
  "String"
]
```
----------------
```javascript
Values[?(@.Coercible !== '1')].Name
```
JSONPath result: 
```javascript
[
  "Number"
]
```

I'm hesitant to include a change to the behavior of ```QueryExpression.EqualsWithStringCoercion``` in the pull request as they might break code in the wild, and is probably something that the core team needs to hash out.
