### ISSUE TITLE
JsonSerializationException at deserialization of a property of name Data

### ISSUE THREAD

**Issue by neshmonin** [JamesNK/Newtonsoft.Json#1860]
Hi guys,
Below is a simple code that throws a JsonSerializationException when executing the last statement of the Main:
### Source
```csharp
class Program
{
    static void Main(string[] args)
    {
        var jsonSettings = new JsonSerializerSettings() { TypeNameHandling = TypeNameHandling.All };
        var theObject = new DerivedClass(new BaseClass() { Data = "abc" });

        string json = JsonConvert.SerializeObject(theObject, Formatting.Indented, jsonSettings);

        // the following call throws the JsonSerializationException:
        DerivedClass deserializedObject = JsonConvert.DeserializeObject<DerivedClass>(json, jsonSettings);
    }
}

public class BaseClass
{
    public string Data { get; set; }
}

public class DerivedClass : BaseClass
{
    public DerivedClass(BaseClass data)
    {
        Data = data.Data;
    }
}
```
Here is a BaseClass with a single string property of name Data. Also we have a DerivedClass that just assigns some string value ("abc") to the Data property.
With TypeNameHandling = TypeNameHandling.All setting we serialize the DerivedClass.
As expected, the json string value comes as:
```javascript
{
  "$type": "ConsoleApplication.DerivedClass, ConsoleApplication",
  "Data": "abc"
}
```
### Expected behavior
When I deserialize the json string back, I'd expect to get deserializedObject of type DerivedClass where Data property is "abc"...

### Actual behavior
Instead, I have a JsonSerializationException:
```csharp
Newtonsoft.Json.JsonSerializationException was unhandled
  HResult=-2146233088
  Message=Error converting value "abc" to type 'ConsoleApplication.BaseClass'. Path 'Data', line 3, position 15.
  Source=Newtonsoft.Json
  StackTrace:
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
       at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
       at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
       at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
       at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
       at ConsoleApplication.Program.Main(String[] args) in C:\Dayforce\SharpTop\UtilitySuite\ConsoleApplication\Program.cs:line 15
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: System.ArgumentException
       HResult=-2147024809
       Message=Could not cast or convert from System.String to ConsoleApplication.BaseClass.
       Source=Newtonsoft.Json
       StackTrace:
            at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
            at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
            at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
       InnerException: 
```
### Steps to reproduce
NOTE: this is very important - you have to execute the above sample 'as is'. I.e.:
- If you rename the BaseClass property from 'Data' to anything else, everything works fine. 
- If you rename the DerivedClass constructor argument name from 'data' to something else, everything works fine.
- If you assign Data property with null or empty string, everything works fine.
- If you add an empty constructor to the DerivedClass, everything works fine.
- If you serialize/deserialize just the BaseClass, everything works fine.

**Comment by JamesNK** [comment]
You get that error because of the constructor: `DerivedClass(BaseClass data)`. Your data string can't be converted to BaseClass.
