### ISSUE TITLE
Error handler can't skip certain malformed string values

### ISSUE THREAD

**Issue by JohnRusk** [JamesNK/Newtonsoft.Json#1868]
I'm trying to get JSON.NET to skip errors in properties when deserializing.  I have a string property that represents a path name. If the user forgets to escape backslashes in the path, Json.NET cannot successfully skip the error.  

Specifically, when handling the first (expected) error, Json.NET hits a second error (inside its handler for the first) and this causes DeserializeObject to return null, instead of returning an instance of my object with the bad property skipped.

### Source/destination types

```csharp
        class TestClass
        {
            public string Foo { get; set; }
        }
```

### Source/destination JSON

```javascript
{
    "Foo" : "d:\aTest"
}
```
**Note** that the backslash here is not escaped. That is the error I'm trying to catch and ignore.

### Expected behavior

DeserializeObject should return an instance of TestClass with the property having its default value.

### Actual behavior

DeserializeObject returns null. Here's some output, with some logging/dumps of errors included:

Note
1. Correct callstack from the first error
2. The second error happens inside JsonSerializerInternalReader.HandleError, so this second error is NOT caught in the JSON.Net code like the first one was.
3. DeserializeObject returns null.

```
Newtonsoft.Json.JsonReaderException: Bad JSON escape sequence: \a. Path 'Foo', line 3, position 16.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)

Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: r. Path 'Foo', line 3, position 16.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.Skip()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.HandleError(JsonReader reader, Boolean readPastError, Int32 initialDepth)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)

Outer object is null
```

### Steps to reproduce

```csharp

            var obj = JsonConvert.DeserializeObject<TestClass>(json, new JsonSerializerSettings()
            {
                Error = (sender, args) =>
                {
                    Console.WriteLine(args.ErrorContext.Error.ToString() + Environment.NewLine);
                    args.ErrorContext.Handled = true;
                }
            });

            Console.WriteLine(obj == null ? "Outer object is null" : "Outer object has value");
        }
```

**Comment by JamesNK** [comment]
This feature was really designed for serialization type conversion errors. Skipping past errors in JSON syntax is always very hit or miss. The reader has no idea what state it should be in when it hits an invalid char, and can't it recover. You will need to use something else to get the results you desire.
