### ISSUE TITLE
JsonConvert.PopulateObject() doesn't play nicely with JsonExtensionDataAttribute

### ISSUE THREAD

**Issue by yuretz** [JamesNK/Newtonsoft.Json#1874]
### Source/destination types

```csharp
public class Something
{
	public int Foo { get; set; }

	[JsonExtensionData]
	public IDictionary<string, JToken> Extra { get; set; }
}
```

#### JSON object 1
```javascript
{"Foo": 1, "Bar": 2}
```
#### JSON object 2
```javascript
{"Foo": 3, "Bar": 4}
```

### Expected behavior

JsonConvert.PopulateObject() should not throw any exceptions when called with a valid JSON and an instance of the `Something` class.

### Actual behavior

The following exception is thrown:
```
Message
Error setting value in extension data for type 'UserQuery+Something'. Path 'Bar', line 1, position 19. 

Source
Newtonsoft.Json 

StackTrace
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetExtensionData(JsonObjectContract contract, JsonProperty member, JsonReader reader, String memberName, Object o)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonConvert.PopulateObject(String value, Object target, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.PopulateObject(String value, Object target)
   at UserQuery.Main()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart() 

TargetSite

RuntimeMethodInfo:
JsonSerializerInternalReader.SetExtensionData (JsonObjectContract contract, JsonProperty member, JsonReader reader, String memberName, Object o)
```

### Steps to reproduce

Please run the following code. Exception is thrown on the second invocation of `JsonConvert.PopulateObject()`.

```csharp
	var something = new Something();
	
	JsonConvert.PopulateObject(@"{""Foo"": 1, ""Bar"": 2}", something);	
	JsonConvert.PopulateObject(@"{""Foo"": 2, ""Bar"": 3}", something);
```
### Versions
Tested on 11.0.2

**Comment by JamesNK** [comment]
Fixed. Thanks for the detailed repo.

**Comment by yuretz** [comment]
Awesome, thank you!
