### ISSUE TITLE
Newtonsoft.Json fails serialization on Stream.ReadTimeout

### ISSUE THREAD

**Issue by AArnott** [JamesNK/Newtonsoft.Json#1898]
Similar to #1470, but with a different goal/outcome in mind... I was actually surprised that Newtonsoft.Json had any support for Streams at all, but it evidently does because it is trying to write it out, I guess. But in my case, the Stream is a MemoryStream, which has no timeouts. So when Newtonsoft.Json calls `Stream.ReadTimeout`, it throws an `InvalidOperationException` which breaks serialization. This exception can be easily avoided by calling `Stream.CanTimeout` first, which would return `false`, indicating that the call to `ReadTimeout` or `WriteTimeout` should be omitted.

> Message: Newtonsoft.Json.JsonSerializationException : Error getting value from 'ReadTimeout' on 'System.IO.MemoryStream'.
---- System.InvalidOperationException : Timeouts are not supported on this stream.

```
Result StackTrace:	
at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.Linq.JToken.FromObjectInternal(Object o, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.FromObject(Object o, JsonSerializer jsonSerializer)
   at StreamJsonRpc.JsonMessageFormatter.TokenizeUserData(Object value) in D:\git\streamjsonrpc\src\StreamJsonRpc\JsonMessageFormatter.cs:line 239
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at StreamJsonRpc.JsonMessageFormatter.TokenizeUserData(JsonRpcMessage jsonRpcMessage) in D:\git\streamjsonrpc\src\StreamJsonRpc\JsonMessageFormatter.cs:line 207
   at StreamJsonRpc.JsonMessageFormatter.Serialize(JsonRpcMessage message) in D:\git\streamjsonrpc\src\StreamJsonRpc\JsonMessageFormatter.cs:line 131
   at StreamJsonRpc.JsonMessageFormatter.Serialize(IBufferWriter`1 contentBuffer, JsonRpcMessage message) in D:\git\streamjsonrpc\src\StreamJsonRpc\JsonMessageFormatter.cs:line 96
   at StreamJsonRpc.HeaderDelimitedMessageHandler.Write(JsonRpcMessage content, CancellationToken cancellationToken) in D:\git\streamjsonrpc\src\StreamJsonRpc\HeaderDelimitedMessageHandler.cs:line 227
   at StreamJsonRpc.PipeMessageHandler.WriteCoreAsync(JsonRpcMessage content, CancellationToken cancellationToken) in D:\git\streamjsonrpc\src\StreamJsonRpc\PipeMessageHandler.cs:line 100
   at StreamJsonRpc.MessageHandlerBase.<WriteAsync>d__15.MoveNext() in D:\git\streamjsonrpc\src\StreamJsonRpc\MessageHandlerBase.cs:line 137
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()
   at StreamJsonRpc.JsonRpc.<InvokeCoreAsync>d__91`1.MoveNext() in D:\git\streamjsonrpc\src\StreamJsonRpc\JsonRpc.cs:line 1107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at StreamPassingTests.<ClientCanSendOneWayStreamToServer>d__6.MoveNext() in D:\git\streamjsonrpc\src\StreamJsonRpc.Tests\StreamPassingTests.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at System.IO.Stream.get_ReadTimeout()
   at GetReadTimeout(Object )
   at Newtonsoft.Json.Serialization.DynamicValueProvider.GetValue(Object target)
Result Message:	
Newtonsoft.Json.JsonSerializationException : Error getting value from 'ReadTimeout' on 'System.IO.MemoryStream'.
---- System.InvalidOperationException : Timeouts are not supported on this stream.
```

**Comment by JamesNK** [comment]
Json.NET just tries to serialize it like a normal object. I wouldn't recommend serializing a Stream, but if you really want to do it then write a JsonConverter.

**Comment by AArnott** [comment]
Ah, I see. I thought it was actually recognizing the Stream, but what you say makes sense as it is just reading properties on the object.
And ya, I don't actually want to serialize a stream's content like this. But I am writing a JsonConverter to translate the Stream into something remotable as part of https://github.com/Microsoft/vs-streamjsonrpc/issues/140
