### ISSUE TITLE
Bug: Concurrency Issue Causing DefaultValue to be Ignored when Using JsonSerializer

### ISSUE THREAD

**Issue by JeremyTCD** [JamesNK/Newtonsoft.Json#1961]
## Version
12.0.1

## Description
I've created a [reproduction repository](https://github.com/JeremyTCD/IssueReproduction.DefaultValueIgnored). It's a simple console application. This is what it contains:

### DummyModel.cs
```csharp
namespace IssueReproduction.DefaultValueIgnored
{
    public class DummyModel
    {
        public DummyModel(int dummyProperty1, int dummyProperty2)
        {
            if (dummyProperty2 != 1)
            {
                throw new Exception("Expected value: 1, Received value: " + dummyProperty2);
            }
        }

        public int DummyProperty1 { get; }

        [JsonProperty(DefaultValueHandling = DefaultValueHandling.Populate), DefaultValue(1)]
        public int DummyProperty2 { get; }
    }
}
```

### Program.cs
```csharp
namespace IssueReproduction.DefaultValueIgnored
{
    class Program
    {
        static void Main(string[] args)
        {
            string json = @"{}";

            while (true)
            {
                var jsonSerializer = new JsonSerializer() { ContractResolver = new DefaultContractResolver() };
                var threads = new Thread[2];
                Exception exception = null;

                for (int i = 0; i < threads.Length; i++)
                {
                    var thread = new Thread(() =>
                    {
                        try
                        {
                            using (var jsonTextReader = new JsonTextReader(new StringReader(json)))
                            {
                                DummyModel result = jsonSerializer.Deserialize<DummyModel>(jsonTextReader);
                            }
                        }
                        catch (Exception e)
                        {
                            exception = e;
                        }
                    });
                    threads[i] = thread;
                }

                threads[0].Start();
                threads[1].Start();

                threads[0].Join();
                threads[1].Join();

                if (exception != null)
                {
                    Console.WriteLine(exception.ToString());
                    break;
                }
            }
        }
    }
}
```

Ctrl+F5 to run the console application. Eventually, the following stack trace will be printed:
```
System.Exception: Expected value: 1, Received value: 0
   at IssueReproduction.DefaultValueIgnored.DummyModel..ctor(Int32 dummyProperty1, Int32 dummyProperty2) in C:\Projects\IssueReproduction.DefaultValueIgnored\IssueReproduction.DefaultValueIgnored\DummyModel.cs:line 15
   at lambda_method(Closure , Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 2031
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 476
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in /_/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs:line 167
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:line 907
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader) in /_/Src/Newtonsoft.Json/JsonSerializer.cs:line 873
   at IssueReproduction.DefaultValueIgnored.Program.<>c__DisplayClass0_1.<Main>b__0() in C:\Projects\IssueReproduction.DefaultValueIgnored\IssueReproduction.DefaultValueIgnored\Program.cs:line 29
Press any key to continue . . .
```

## Cause
I've isolated the cause to `JsonObjectContract.HasRequiredOrDefaultValueProperties`:

https://github.com/JamesNK/Newtonsoft.Json/blob/7217c484e9705b5e76585c8b7fcd489c8e021c23/Src/Newtonsoft.Json/Serialization/JsonObjectContract.cs#L136-L163

The first thread sets `_hasRequiredOrDefaultValueProperties` to false before scanning through properties:

https://github.com/JamesNK/Newtonsoft.Json/blob/7217c484e9705b5e76585c8b7fcd489c8e021c23/Src/Newtonsoft.Json/Serialization/JsonObjectContract.cs#L140-L142

If it the second thread  hits line 140 before the first thread sets `_hasRequiredOrDefaultValueProperties` to true, `JsonObjectContract.HasRequiredOrDefaultValueProperties` erroneously returns false.

This causes `trackPresence` to be set to false in `JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters`:

https://github.com/JamesNK/Newtonsoft.Json/blob/7217c484e9705b5e76585c8b7fcd489c8e021c23/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs#L1890

Which, in turn, causes `propertyContexts` to be empty:

https://github.com/JamesNK/Newtonsoft.Json/blob/7217c484e9705b5e76585c8b7fcd489c8e021c23/Src/Newtonsoft.Json/Serialization/JsonSerializerInternalReader.cs#L1905-L1919

## Suggested Fix
Add a double checked lock and make `_hasRequiredOrDefaultValueProperties` volatile. This will fix the issue and won't affect performance.

## Workaround
Include `DefaultValueHandling.Populate` flag for `JsonSerializer.DefaultValueHandling` or create a JsonSerializer for each thread.

**Comment by xiaoxiaotank** [comment]
We observed the same behavior with Newtonsoft.Json 13.0.3: during the first parallel deserialization, a missing property configured with `DefaultValueHandling.Populate` occasionally keeps its constructor-initialized value instead of being populated with the configured default value. The issue does not reproduce in single-threaded scenarios and disappears after the contract has been initialized.

The behavior appears to match the race condition in `HasRequiredOrDefaultValueProperties` described here. A thread-safe initialization of this cached value seems like a reasonable fix.

We are currently using a separate serializer per thread as a workaround. Since this can result in silently incorrect deserialized data, we hope this issue can be investigated and fixed in an upcoming release.

Thank you.
