### ISSUE TITLE
Issue with invalid syntax

### ISSUE THREAD

**Issue by mmarzullo** [JamesNK/Newtonsoft.Json#2133]
### Description
Was found that when sending no value for a field, no value is taken as _undefined_.
If I have a **body** like this:

```JSON
{
    "exampleA": false,	
    "exampleB": ,
}
```
### Result
Deserialize(body) return:

```java
{
    "exampleA": false,	
    "exampleB": undefined
}
```
but that **body** should be an invalid input. ([oficial JSON](https://www.json.org))

### Expected
```java
{
    "": [
            "The input was not valid."
        ]
}
```

**Comment by JamesNK** [comment]
Json.NET supports reading non-standard JSON. This is an example.

**Comment by mmarzullo** [comment]
I've done some research and here's a better explanation of the current problem:

I'll include two classes, two JSON examples and the corresponding two results after trying to deserialize them using `JsonConvert.DeserializeObject()`

Classes:
___
```c#
public class Class1
{
     // property is of type <<object>>
     public object Property1 { get; set; }
}
```
```c#
public class Class2
{
     // property is of type <<bool>>
     public bool Property2 { get; set; }
}
```
JSON examples (**one key, no value**):
___
```json
{
    "Property1": ,
}
```
```json
{
    "Property2": ,
}
```
1. The first attempt, the one that uses Class1 and Property1, correctly transforms the `undefined` value into a `null` value
2. The second attempt, which uses Class2 and Property2, throws the following exception:
```
Message    "Unexpected character encountered while parsing value: ,. Path 'Property2', line 2, position 14."    string
StackTrace	
at Newtonsoft.Json.JsonTextReader.ProcessValueComma()
at Newtonsoft.Json.JsonTextReader.ReadAsBoolean()
at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings set
```

There seems to be some "inconsistency" between the logic that deserializes objects and bools. Is this a bug on your side?

**Comment by JamesNK** [comment]
That's not a bug. "undefined" is a valid token. But an "undefined" bool value doesn't make sense, so it fails.

**Comment by joaco-espinosa** [comment]
@JamesNK What if the example above uses `bool?` (nullable) instead of `bool`? Does that change your answer?
It seems that `undefined` should be a valid value for a nullable field.

**Comment by mmarzullo** [comment]
that is the point, `bool` nullable generates an inconsistency.
