### ISSUE TITLE
System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.SortedSet`1' to type 'System.Collections.IList'.

### ISSUE THREAD

**Issue by yyjdelete** [JamesNK/Newtonsoft.Json#2148]
Maybe the same as #1796.

### Source/destination types

```csharp
        public class Model
        {
            public int A { get; }
            public IEnumerable<string> B { get; } = new SortedSet<string>();

            //[JsonConstructor]
            public Model(int a)
            {
                this.A = a;
            }
        }
```

### Source/destination JSON

```javascript
{'a':1,'b':['aaa']}
```

### Expected behavior

Work as it does without the `.ctor(int)`(JsonConstructor).

### Actual behavior

```cs
System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.SortedSet`1[System.String]' to type 'System.Collections.IList'.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
```

### Steps to reproduce
Update the test to also include an test for readonlyList (https://github.com/JamesNK/Newtonsoft.Json/issues/2148#issuecomment-527708042)
```csharp
        var a = JsonConvert.DeserializeObject<Model>("{'a':1,'b':['aaa'],'c':['aaa']}");

        public class Model
        {
            public int A { get; }
            public IEnumerable<string> B { get; } = new SortedSet<string>();
            public IEnumerable<string> C { get; } = new List<string>().AsReadOnly();

            //[JsonConstructor]
            public Model(int a)
            {
                this.A = a;
            }
        }
```

**Comment by yyjdelete** [comment]
```cs
        public class Model
        {
            public int A { get; }
            public IEnumerable<string> B { get; } = new List<string>().AsReadOnly();//= new SortedSet<string>();

            //[JsonConstructor]
            public Model(int a)
            {
                this.A = a;
            }
        }
```

```cs
Unhandled exception. System.NotSupportedException: Collection is read-only.
   at System.Collections.ObjectModel.ReadOnlyCollection`1.System.Collections.IList.Add(Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(JsonReader reader, JsonObjectContract objectContract, JsonProperty containerMember, JsonProperty containerProperty, String id, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
```

**Comment by yyjdelete** [comment]
An full test to show the different behavior with/without `JsonConstructor`

And use propertyType can only fix the `InvalidCastException` and `NotSupportedException`
Still have some different behavior(see the comments in the test below) for `Extension`(JsonExtensionData), `E`(object) and the result of SerializeObject, and not sure if `D`(JObject) should also be populate.

```cs
object? propertyValue = property.ValueProvider!.GetValue(createdObject);
if (propertyValue == null)
{
    context.Used = true;
    continue;
}
JsonContract propertyContract = Serializer._contractResolver.ResolveContract(propertyValue.GetType());
```

<details>

```cs

    [TestFixture]
    public class Issue2148 : TestFixtureBase
    {
        [Test]
        public void Test()
        {
            var data = "{'A':2148,'B':['aaa'],'C':['bbb'],'D':{'A':'ccc'},'E':{'A':'ddd'},'F':{'A':'eee'},'G':{'A':'fff'},'H':'ggg'}";
            var expected = JsonConvert.DeserializeObject<ModelWithoutCtor>(data);
            var actual = JsonConvert.DeserializeObject<ModelWithCtor>(data);

            Assert.AreEqual(expected.A, actual.A);
            Assert.AreEqual(expected.B.Count(), actual.B.Count());//InvalidCastException
            Assert.AreEqual(expected.C.Count, actual.C.Count);//NotSupportedException: Collection is read-only.
            Assert.AreEqual(expected.D.Count, actual.D.Count);//Expected(should JObject also be populated?): 0, Actual: InvalidCastException
            Assert.AreEqual(expected.E.A, actual.E.A);//Expected: "ddd", Actual: null
            Assert.AreEqual(expected.F.Count, actual.F.Count);//InvalidCastException
            Assert.AreEqual(expected.Extension.Count, actual.Extension.Count);//Expected: 2, Actual: 1
            //Expected: "C,G,H", Actual: "H"
            Assert.AreEqual(string.Join(",", ((IDictionary<string, JToken>)expected.Extension).Keys),
                string.Join(",", ((IDictionary<string, JToken>)actual.Extension).Keys));

            //Expected(double C and G?): {"A":2148,"B":["aaa"],"C":[],"D":{},"E":{"A":"ddd"},"F":{"A":"eee"},"G":null,"C":["bbb"],"G":{"A":"fff"},"H":"ggg"}
            //Actual:   {"A":2148,"B":["aaa"],"C":[],"D":{},"E":{"A":null},"F":{"A":"eee"},"G":null,"H":"ggg"}
            Assert.AreEqual(JsonConvert.SerializeObject(expected), JsonConvert.SerializeObject(actual));
        }

        public class ModelWithCtor
        {
            public int A { get; }
            //IEnumerable<T> is needed here, use ICollection<T> will not throw.
            public IEnumerable<string> B { get; } = new SortedSet<string>();
            public ICollection<string> C { get; } = new List<string>().AsReadOnly();
            public IDictionary<string, JToken> D { get; } = new JObject();
            public Model3 E { get; } = new Model3();
            public IDictionary<string, string> F { get; } = new GenericDictionaryWarpper();
            public IDictionary<string, string> G { get; } = null;
            [JsonExtensionData]
            public JObject Extension { get; set; }

            [JsonConstructor]
            public ModelWithCtor(int a)
            {
                this.A = a;
            }
        }

        public class ModelWithoutCtor
        {
            public int A { get; set; }
            public IEnumerable<string> B { get; } = new SortedSet<string>();
            public ICollection<string> C { get; } = new List<string>().AsReadOnly();
            public IDictionary<string, JToken> D { get; } = new JObject();
            public Model3 E { get; } = new Model3();
            public IDictionary<string, string> F { get; } = new GenericDictionaryWarpper();
            public IDictionary<string, string> G { get; } = null;
            [JsonExtensionData]
            public JObject Extension { get; set; }
        }

        public class Model3
        {
            public string A { get; set; }
        }

        public class GenericDictionaryWarpper : IDictionary<string, string>
        {
            private readonly IDictionary<string, string> wrapper = new Dictionary<string, string>();

            public string this[string key] { get => wrapper[key]; set => wrapper[key] = value; }

            public ICollection<string> Keys => wrapper.Keys;

            public ICollection<string> Values => wrapper.Values;

            public int Count => wrapper.Count;

            public bool IsReadOnly => wrapper.IsReadOnly;

            public void Add(string key, string value)
            {
                wrapper.Add(key, value);
            }

            public void Add(KeyValuePair<string, string> item)
            {
                wrapper.Add(item);
            }

            public void Clear()
            {
                wrapper.Clear();
            }

            public bool Contains(KeyValuePair<string, string> item)
            {
                return wrapper.Contains(item);
            }

            public bool ContainsKey(string key)
            {
                return wrapper.ContainsKey(key);
            }

            public void CopyTo(KeyValuePair<string, string>[] array, int arrayIndex)
            {
                wrapper.CopyTo(array, arrayIndex);
            }

            public IEnumerator<KeyValuePair<string, string>> GetEnumerator()
            {
                return wrapper.GetEnumerator();
            }

            public bool Remove(string key)
            {
                return wrapper.Remove(key);
            }

            public bool Remove(KeyValuePair<string, string> item)
            {
                return wrapper.Remove(item);
            }

            public bool TryGetValue(string key, out string value)
            {
                return wrapper.TryGetValue(key, out value);
            }

            IEnumerator IEnumerable.GetEnumerator()
            {
                return wrapper.GetEnumerator();
            }
        }
    }
```

</details>

**Comment by JamesNK** [comment]
Thanks for the good repro. Fixed!

**Comment by yyjdelete** [comment]
@JamesNK
Maybe also consider the different behavior for class with/without `JsonConstructor`, not sure if it's expected?

The code copy from https://github.com/JamesNK/Newtonsoft.Json/issues/2148#issuecomment-529077570
```cs
    [TestFixture]
    public class Issue2148 : TestFixtureBase
    {
        [Test]
        public void Test()
        {
            var data = "{'A':2148,'B':['aaa'],'C':['bbb'],'D':{'A':'ccc'},'E':{'A':'ddd'},'F':{'A':'eee'},'G':{'A':'fff'},'H':'ggg'}";
            var expected = JsonConvert.DeserializeObject<ModelWithoutCtor>(data);
            var actual = JsonConvert.DeserializeObject<ModelWithCtor>(data);

            Assert.AreEqual(expected.A, actual.A);
            Assert.AreEqual(expected.B.Count(), actual.B.Count());//InvalidCastException
            Assert.AreEqual(expected.C.Count, actual.C.Count);//NotSupportedException: Collection is read-only.
            Assert.AreEqual(expected.D.Count, actual.D.Count);//Expected(should JObject also be populated?): 0, Actual: InvalidCastException
            Assert.AreEqual(expected.E.A, actual.E.A);//Expected: "ddd", Actual: null
            Assert.AreEqual(expected.F.Count, actual.F.Count);//InvalidCastException
            Assert.AreEqual(expected.Extension.Count, actual.Extension.Count);//Expected: 2, Actual: 1
            //Expected: "C,G,H", Actual: "H"
            Assert.AreEqual(string.Join(",", ((IDictionary<string, JToken>)expected.Extension).Keys),
                string.Join(",", ((IDictionary<string, JToken>)actual.Extension).Keys));

            //Expected(double C and G?): {"A":2148,"B":["aaa"],"C":[],"D":{},"E":{"A":"ddd"},"F":{"A":"eee"},"G":null,"C":["bbb"],"G":{"A":"fff"},"H":"ggg"}
            //Actual:   {"A":2148,"B":["aaa"],"C":[],"D":{},"E":{"A":null},"F":{"A":"eee"},"G":null,"H":"ggg"}
            Assert.AreEqual(JsonConvert.SerializeObject(expected), JsonConvert.SerializeObject(actual));
        }

        public class ModelWithCtor
        {
            public int A { get; }
            //IEnumerable<T> is needed here, use ICollection<T> will not throw.
            public IEnumerable<string> B { get; } = new SortedSet<string>();
            public ICollection<string> C { get; } = new List<string>().AsReadOnly();
            public IDictionary<string, JToken> D { get; } = new JObject();
            public Model3 E { get; } = new Model3();
            public IDictionary<string, string> F { get; } = new GenericDictionaryWarpper();
            public IDictionary<string, string> G { get; } = null;
            [JsonExtensionData]
            public JObject Extension { get; set; }

            [JsonConstructor]
            public ModelWithCtor(int a)
            {
                this.A = a;
            }
        }

        public class ModelWithoutCtor
        {
            public int A { get; set; }
            public IEnumerable<string> B { get; } = new SortedSet<string>();
            public ICollection<string> C { get; } = new List<string>().AsReadOnly();
            public IDictionary<string, JToken> D { get; } = new JObject();
            public Model3 E { get; } = new Model3();
            public IDictionary<string, string> F { get; } = new GenericDictionaryWarpper();
            public IDictionary<string, string> G { get; } = null;
            [JsonExtensionData]
            public JObject Extension { get; set; }
        }

        public class Model3
        {
            public string A { get; set; }
        }

        public class GenericDictionaryWarpper : IDictionary<string, string>
        {
            private readonly IDictionary<string, string> wrapper = new Dictionary<string, string>();

            public string this[string key] { get => wrapper[key]; set => wrapper[key] = value; }

            public ICollection<string> Keys => wrapper.Keys;

            public ICollection<string> Values => wrapper.Values;

            public int Count => wrapper.Count;

            public bool IsReadOnly => wrapper.IsReadOnly;

            public void Add(string key, string value)
            {
                wrapper.Add(key, value);
            }

            public void Add(KeyValuePair<string, string> item)
            {
                wrapper.Add(item);
            }

            public void Clear()
            {
                wrapper.Clear();
            }

            public bool Contains(KeyValuePair<string, string> item)
            {
                return wrapper.Contains(item);
            }

            public bool ContainsKey(string key)
            {
                return wrapper.ContainsKey(key);
            }

            public void CopyTo(KeyValuePair<string, string>[] array, int arrayIndex)
            {
                wrapper.CopyTo(array, arrayIndex);
            }

            public IEnumerator<KeyValuePair<string, string>> GetEnumerator()
            {
                return wrapper.GetEnumerator();
            }

            public bool Remove(string key)
            {
                return wrapper.Remove(key);
            }

            public bool Remove(KeyValuePair<string, string> item)
            {
                return wrapper.Remove(item);
            }

            public bool TryGetValue(string key, out string value)
            {
                return wrapper.TryGetValue(key, out value);
            }

            IEnumerator IEnumerable.GetEnumerator()
            {
                return wrapper.GetEnumerator();
            }
        }
    }
```
