### ISSUE TITLE
Order of "$id" during deserialization matters

### ISSUE THREAD

**Issue by gratinierer** [JamesNK/Newtonsoft.Json#2202]
### Source/destination types
Using following Class Binding:
```csharp
    public class PropertyMapping
    {
        [DataMember(Name = "$id", IsRequired = true)]
        public string ID;

        [DataMember(Name = "Properties", IsRequired = true)]
        public List<TacProperty> SystemProperties = new List<TacProperty>();

        [DataMember(Name = "IsPK", IsRequired = false)]
        public bool IsPk;
    }
```

### Source/destination JSON
deserializing following json works fine:
```javascript
  "Mapping": [
    {
      "IsPK": "false",
      "$id": "#ASpecialIntVal",
      "Properties": [
        {
          "Name": "propint",
          "System": {
            "$ref": "#CSVReader"
          }
        },
        {
          "Name": "propinteger",
          "System": {
            "$ref": "#Client1"
          }
        }
      ]
    },
```
And we get the correct IDs deserialized in to the Objects.
But if the `$id` as the first element of the json-object, 

```javascript
 "Mapping": [
    {
      "$id": "#ASpecialIntVal",
      "IsPK": "false",
      "Properties": [
        {
          "Name": "propint",
          "System": {
            "$ref": "#CSVReader"
          }
        },
        {
          "Name": "propinteger",
          "System": {
            "$ref": "#Client1"
          }
        }
      ]
    },
```

the deserialization fails with

```
Newtonsoft.Json.JsonSerializationException : Required property '$id' not found in JSON. Path 'Mapping[0]', line 40, position 5.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EndProcessProperty(Object newObject, JsonReader reader, JsonObjectContract contract, Int32 initialDepth, JsonProperty property, PropertyPresence presence, Boolean setDefaultValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)

```
### Expected behavior
The value of `$id` should be deserialized independent of the poistion within the object.

Tested with 12.0.2

**Comment by JamesNK** [comment]
`$id` has a special meaning to Json.NET. Disable it with `MetadataPropertyHandling.Ignore`.

https://www.newtonsoft.com/json/help/html/DeserializeMetadataPropertyHandling.htm

**Comment by gratinierer** [comment]
Hi @JamesNK ,

trying
``` c#            
            var serializer = new JsonSerializer()
            {
                MetadataPropertyHandling = MetadataPropertyHandling.ReadAhead
            };

```
i get
``
Newtonsoft.Json.JsonSerializationException : Required property '$id' not found in JSON. Path 'SystemA', line 4, position 14.
``
With
``` C#
            var serializer = new JsonSerializer()
            {
                MetadataPropertyHandling = MetadataPropertyHandling.Ignore
            };
```
I also get an exception:
```
Required property '$id' not found in JSON. Path 'Mapping[0].Properties[0].System', line 31, position 11.
```

But in that case i thing, that this error occurs at the point i'm referencing the `$id`:
```
  "Mapping": [
    {
      "IsPK": "false",
      "$id": "#ASpecialIntVal",
      "Properties": [
        {
          "Name": "propint",
          "System": {
            "$ref": "#CSVReader"
          }
        },
```
I think `Ignore` let's forces the parser not to handle the `$id` as a valid id tag.

Imho there isn't an option at that moment, with that:
* the library doesn't care about the position of the `$id` 
* the library handles the `$id` as a valid json `$id`, that can be used for a `$ref`-tag
* `$id` can be bound to a class property, so value of `$id` can be accessed from my application

Is my assumption correct?
Thank's and bye

**Comment by jmiller12345** [comment]
Hi James, 

I was just wondering if this has been addressed/resolved.  I have a similar issue where I cannot guarantee that the $id will be first in my JSONObject.  I also can't disable this (MetadataPropertyHandling = MetadataPropertyHandling.Ignore) because I have referenced objects (PreserveReferencesHandling = PreserveReferencesHandling.Objects).  I'm currently testing with 13.0.2, and I'm sure it is a longshot that this has been fixed in 13.0.3, but I have to ask.

Is there any other settings that I can use to be able to read ahead the $id value?

Thank you so much.

-John
