### ISSUE TITLE
Cross-context deseserializing to types in collectible assembly contexts fails

### ISSUE THREAD

**Issue by bartico6** [JamesNK/Newtonsoft.Json#2409]
**Short description:** Deserializing a type with the jsonproperty `TypeNameHandling = TypeNameHandling.All` that resides in an assembly context that is collectible fails.

**Exception**:
```
[2020-10-18 20:33:39 ERROR]: An unhandled exception was thrown while loading plugin [collectible assembly short name]: Newtonsoft.Json.JsonSerializationException: Error resolving type specified in JSON '[full type name], [collectible assembly short name]'. Path '[redacted].$type', line 5, position 79.
 ---> System.IO.FileLoadException: Could not load file or assembly '[collectible assembly fullname]'. Operation is not supported. (0x80131515)
File name: '[collectible assembly fullname]'
 ---> System.NotSupportedException: Resolving to a collectible assembly is not supported.
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly assemblyContext, StackCrawlMark& stackMark, Boolean throwOnFileNotFound, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext)
   at System.Reflection.Assembly.LoadWithPartialName(String partialName)
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey(StructMultiKey`2 typeNameKey)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get(TKey key)
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeByName(StructMultiKey`2 typeNameKey)
   at Newtonsoft.Json.Serialization.DefaultSerializationBinder.BindToType(String assemblyName, String typeName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
```

**Reproduction**:
A host app loads Newtonsoft.Json into the Default AssemblyLoadContext, and a plugin assembly into its own collectible AssemblyLoadContext.

The plugin assembly then calls JsonConvert.DeserializeObject from Newtonsoft.Json cross-context (when the CLR attempts to resolve the reference to Newtonsoft.Json, its given the assembly's instance from default context) and attempts to deserialize a json structure that contains a typename from the unloadable plugin assembly.

Newtonsoft.Json, while trying to instantiate the type, calls Assembly.LoadWithPartialName, assembly resolution occurs in the Default context, and it's pointed at the plugin assembly in the collectible context - the exception is thrown, because its collectible.

**Relevant information about the setup:**

The setup is a server app with assembly unloadability on plugins, with plugins being able to freely call all assemblies loaded into the default context (the context where the server itself resides)

**Relevant versions:**

.NET Core 3.1.9
Newtonsoft.Json 12.0.3

**Comment by bartico6** [comment]
For anyone bumping into this in the future thinking what the problem is:

*Assembly unloadability and AppDomain.CurrentDomain.AssemblyResolve don't mix*.

If you're using unloadability, use `AssemblyLoadContext.Default.Resolving` instead.

Sincere apologies for putting the blame on NJson, it was incorrect assembly loading on my part after all.
