### ISSUE TITLE
Cannot resolve contract for Nullable struct dictionary types

### ISSUE THREAD

**Issue by billings7** [JamesNK/Newtonsoft.Json#2450]
Resolving the contract of a nullable value type that implements a dictionary interface that should be handled as a dictionary instead throws an exception.

### Steps to reproduce

```csharp
var resolver = new DefaultContractResolver();
var contract = resolver.ResolveContract(typeof(Dict?));

// Any struct that implements IReadOnlyDictionary/IDictionary/etc
public struct Dict : IReadOnlyDictionary<string, object?>
{
    private readonly IReadOnlyDictionary<string, object?> _dict;
    public Dict(IReadOnlyDictionary<string, object?> dict) => _dict = dict;

    public object? this[string key] => _dict[key];
    public IEnumerable<string> Keys => _dict.Keys;
    public IEnumerable<object?> Values => _dict.Values;
    public int Count => _dict.Count;
    public bool ContainsKey(string key) => _dict.ContainsKey(key);
    public IEnumerator<KeyValuePair<string, object?>> GetEnumerator() => _dict.GetEnumerator();
    public bool TryGetValue(string key, [MaybeNullWhen(false)] out object? value) => _dict.TryGetValue(key, out value);
    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}
```

### Expected behavior

The contract is returned.

### Actual behavior

```
System.Exception: Type System.Nullable`1[Dict] is not a dictionary.
   at Newtonsoft.Json.Utilities.ReflectionUtils.GetDictionaryKeyValueTypes(Type dictionaryType, Type& keyType, Type& valueType)
   at Newtonsoft.Json.Serialization.JsonDictionaryContract..ctor(Type underlyingType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateDictionaryContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at UserQuery.Main(), line 3
```

Looks like `DefaultContractResolver.CreateContract` correctly strips the `Nullable` type and detects it as a dictionary, but the `JsonDictionaryContract` constructor is using the `underlyingType` parameter when it should probably be using `NonNullableUnderlyingType` (as `JsonArrayContract` does).

**Comment by JamesNK** [comment]
Thanks for the bug report. Fixed!
