### ISSUE TITLE
Deserializing SqlException throws an InvalidCastException converting a JValue to a Guid - ClientConnectionId is wrong type

### ISSUE THREAD

**Issue by briangru** [JamesNK/Newtonsoft.Json#2466]
I'm serializing a SqlException, sending it across the wire, then deserializing it.  The endpoints are running .NET Core 3.1 or .NET 5.
I get an InvalidCastException in SqlException's deserialization constructor.  Looks like the ClientConnectionId should be a GUID, but JSON.NET seems to have screwed it up somehow.  Maybe JSON.NET struggles with Guids?

### Source/destination types

System.Data.SqlClient.SqlException

### Expected behavior

Expected we can deserialize a SqlException.  Here are some relevent parts of the code:

        private Guid _clientConnectionId = Guid.Empty;

        private SqlException(SerializationInfo si, StreamingContext sc) : base(si, sc) 
        {
            HResult = SqlExceptionHResult;
            foreach (SerializationEntry siEntry in si)
            {
                if ("ClientConnectionId" == siEntry.Name) 
                {
                    _clientConnectionId = (Guid)siEntry.Value;
                    break;
                }
            }
        }

And here we add a Guid:
        public override void GetObjectData(SerializationInfo si, StreamingContext context)
        {
            base.GetObjectData(si, context);
            si.AddValue("Errors", null); // Not specifying type to enable serialization of null value of non-serializable type
            si.AddValue("ClientConnectionId", _clientConnectionId, typeof(Guid));

### Actual behavior

Failed to log in.  ServerError  System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'System.Guid'.
   at System.Data.SqlClient.SqlException..ctor(SerializationInfo si, StreamingContext sc)
   at lambda_method(Closure , Object[] )
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializable(JsonReader reader, JsonISerializableContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
[..snip..]

### Steps to reproduce

        private static void Serialize(Object obj, TextWriter writer, Formatting jsonFormatting = Formatting.Indented)
        {
            JsonSerializer serializer = new JsonSerializer();
            serializer.TypeNameHandling = TypeNameHandling.All;
            JsonWriter jsonWriter = new JsonTextWriter(writer);
            jsonWriter.Formatting = jsonFormatting;
            serializer.Serialize(jsonWriter, obj);
            jsonWriter.Flush();
        }

        public static T Deserialize<T>(Stream stream)
        {
            JsonSerializer deserializer = new JsonSerializer();
            deserializer.TypeNameHandling = TypeNameHandling.All;
            deserializer.SerializationBinder = TypeRenameSerializationBinder.Default;
            StreamReader reader = new StreamReader(stream);
            JsonReader jsonReader = new JsonTextReader(reader);
            T obj = deserializer.Deserialize<T>(jsonReader);
            return obj;
        }

**Comment by elgonzo** [comment]
Json.NET normally does not have trouble serializing and deserializing System.Guid instances.

What is that mysterious `TypeRenameSerializationBinder` you are using? There, in this line in your Deserialize<T> method:
```
deserializer.SerializationBinder = TypeRenameSerializationBinder.Default;
```
The name of it suggests some type renaming shenanigans, and i strongly feel that this might be related to your troubles.
