### ISSUE TITLE
MaxDepth default value of `null` or `100` is not respected

### ISSUE THREAD

**Issue by Smaug123** [JamesNK/Newtonsoft.Json#2501]
### Source/destination types

Code expressed in F#, sorry. Serialisation is fine; deserialisation is not.

```fsharp
type Foo =
| Foo of Foo
| Bar of int
```

### Source/destination JSON

This is very, very long - sorry.

```javascript
{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Bar","Fields":[3]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}
```

### Expected behavior

As documented, the `MaxDepth` property being null should mean there is no max depth, and we should get a deserialisation.

### Actual behavior

On Newtonsoft.Json 13.0.1 only (I checked 12.0.3 and it was fine), the following exception is thrown:
```
Newtonsoft.Json.JsonReaderException: The reader's MaxDepth of 64 has been exceeded. Path 'Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0].Fields[0]', line 1, position 769.
   at Newtonsoft.Json.JsonReader.Push(JsonContainerType value)
   at Newtonsoft.Json.JsonReader.SetToken(JsonToken newToken, Object value, Boolean updateIndex)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JArray.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Converters.DiscriminatedUnionConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Foo.Test.TestNewtonsoft.property@99-4.Invoke(Foo f) in /Users/Patrick/Documents/GitHub/Foo/Foo.Test/TestNewtonsoft.fs:line 99
   at FsCheck.Testable.evaluate[a,b](FSharpFunc`2 body, a a)
```

### Steps to reproduce

Package versions:
```
        <PackageReference Update="FSharp.Core" Version="5.0.1" />
        <PackageReference Include="FsCheck" Version="2.15.1" />
        <PackageReference Include="FsUnit" Version="4.0.4" />
        <PackageReference Include="NUnit" Version="3.13.1" />
        <PackageReference Include="NUnit3TestAdapter" Version="3.16.1" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
```

Specific example that fails (in F#):

```fsharp
    [<Test>]
    let ``Extracted example`` () =
        let example = """{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Foo","Fields":[{"Case":"Bar","Fields":[3]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}]}"""
        let settings = JsonSerializerSettings ()
        settings.MaxDepth <- System.Nullable ()

        JsonConvert.DeserializeObject<Foo> (example, settings)
        |> ignore
```

Property-based test (again in F#) that consistently fails:

```fsharp
open FsCheck
open Newtonsoft.Json

[<TestFixture>]
module TestNewtonsoft =
    let rec generator () : Gen<Foo> =
        gen {
            let! i = Gen.choose (0, 99)
            if i < 95 then
                let! result = generator ()
                return Foo result
            else
                return Bar 3
        }

    [<Test>]
    let ``Test Newtonsoft`` () =
        let settings = JsonSerializerSettings ()
        settings.MaxDepth <- System.Nullable ()
        let property (f : Foo) =
            JsonConvert.SerializeObject (f, settings)
            |> fun s -> JsonConvert.DeserializeObject<Foo> (s, settings)
            |> (=) f

        property
        |> Prop.forAll (Arb.fromGen (generator ()))
        |> Check.QuickThrowOnFailure
```

**Comment by Smaug123** [comment]
I've observed this behaviour with `System.Nullable System.Int32.MaxValue` and with `Int32.MaxValue - 1`, as well. I have not yet found a workaround that allows a depth greater than 64, other than downgrading Newtonsoft.Json.

**Comment by shawnallen85** [comment]
Is there a planned release that will include this fix?

**Comment by Smaug123** [comment]
@JamesNK could you please cut a new Newtonsoft.Json with this fix in? We periodically have people rediscovering this bug and downgrading.

**Comment by MinhThienDX** [comment]
@Smaug123 Would you kindly try the latest version released on 24 Nov?
https://github.com/JamesNK/Newtonsoft.Json/releases/latest
