### ISSUE TITLE
jsonschema.parse not following $ref

### ISSUE THREAD

**Issue by jeffpatton1971** [JamesNK/Newtonsoft.Json#2546]
The code below only fails when a schema has a $ref inside, you can see the sample schema below. This schema works in the online validator, but when I pass in a url to the schema it fails.

### Csharp Code

```C#
WebClient wget = new System.Net.WebClient();
var jsonSchema = wget.DownloadString(request.Schema);

JSchema schema = JSchema.Parse(jsonSchema);
```

### Source/destination JSON

```json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "id": "https://raw.githubusercontent.com/jeffpatton1971/randomschema/main/resources/resources.json",
  "title": "Resources",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "definedResources": {
      "type": "array",
      "items": {
        "$ref": "https://raw.githubusercontent.com/jeffpatton1971/randomschema/main/resources/definedResource.json"
      }
    }
  }
}
```
### returned from DownloadString

```
"{\n  \"$schema\": \"http://json-schema.org/draft-06/schema#\",\n  \"id\": \"https://raw.githubusercontent.com/jeffpatton1971/randomschema/main/resources/resources.json\",\n  \"title\": \"Resources\",\n  \"type\": \"object\",\n  \"additionalProperties\": false,\n  \"properties\": {\n    \"definedResources\": {\n      \"type\": \"array\",\n      \"items\": {\n        \"$ref\": \"https://raw.githubusercontent.com/jeffpatton1971/randomschema/main/resources/definedResource.json\"\n      }\n    }\n  }\n}\n"
```

### Expected behavior

I expected it to read in the reference, this works on the online newtonsoft validator, but it's accepting a string schema vs URL, like my code above.

### Actual behavior

Newtonsoft.Json.Schema.JSchemaReaderException: Could not resolve schema reference 'https://raw.githubusercontent.com/jeffpatton1971/randomschema/main/resources/definedResource.json'. Path 'properties.definedResources.items', line 10, position 16.
   at Newtonsoft.Json.Schema.Infrastructure.JSchemaReader.ResolveDeferedSchema(DeferedSchema deferedSchema)
   at Newtonsoft.Json.Schema.Infrastructure.JSchemaReader.ResolveDeferedSchemas()
   at Newtonsoft.Json.Schema.Infrastructure.JSchemaReader.ReadRoot(JsonReader reader, Boolean resolveDeferedSchemas)
   at Newtonsoft.Json.Schema.Infrastructure.JSchemaReader.ReadRoot(JsonReader reader)
   at Newtonsoft.Json.Schema.JSchema.Load(JsonReader reader, JSchemaReaderSettings settings)
   at Newtonsoft.Json.Schema.JSchema.Parse(String json, JSchemaReaderSettings settings)
   at Newtonsoft.Json.Schema.JSchema.Parse(String json)
   at baapi.Controllers.JsonController.GetJson(JsonRequest request) in D:\CODE\Organizations\global-build\baapi\baapi\Controllers\JsonController.cs:line 105
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Connection: close
Content-Length: 109
Content-Type: application/json
Host: localhost:44387
Referer: https://localhost:44387/index.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"
sec-ch-ua-mobile: ?0
origin: https://localhost:44387
sec-fetch-site: same-origin
sec-fetch-mode: cors
sec-fetch-dest: empty

**Comment by elgonzo** [comment]
Try using `JSchemaUrlResolver` as per documentation at: https://www.newtonsoft.com/jsonschema/help/html/LoadingSchemas.htm (section "_Resolving externally referenced schemas_").

(P.S.: Wrong issue tracker :) Newtonsoft.Json.Schema has its own issue tracker at https://github.com/JamesNK/Newtonsoft.Json.Schema/issues)

**Comment by jeffpatton1971** [comment]
Thanks so much @elgonzo ! and I'll make sure to check where i drop issues in the future ;-)
