### ISSUE TITLE
IndexOutOfRangeException in DefaultJsonNameTable.Get() on devices with ARM cpu

### ISSUE THREAD

**Issue by AlanLiu90** [JamesNK/Newtonsoft.Json#2598]
I wrote a program to reproduce this issue on my Raspberry Pi:
```csharp
using System;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading;
using Newtonsoft.Json;

namespace TestJson
{
    class Program
    {
        static Random random = new Random();
        static string[] randomStrings;

        static void Main(string[] args)
        {
            Console.WriteLine("CPU Arch: {0}, Processor count: {1}", 
                RuntimeInformation.ProcessArchitecture, Environment.ProcessorCount);

            int cnt = 1;
            while (true)
            {
                var nameTable = new DefaultJsonNameTable();

                randomStrings = new string[10000];
                for (int i = 0; i < randomStrings.Length; ++i)
                    randomStrings[i] = RandomString(20);

                Thread[] threads = new Thread[3];
                for (int i = 0; i < threads.Length; ++i)
                    threads[i] = new Thread(x => RunGet(nameTable));

                Thread t = new Thread(x => RunAdd(nameTable));

                for (int i = 0; i < threads.Length; ++i)
                    threads[i].Start();

                t.Start();

                for (int i = 0; i < threads.Length; ++i)
                    threads[i].Join();

                t.Join();

                cnt++;
                if (cnt % 100 == 0)
                    Console.WriteLine(cnt);
            }
        }

        static void RunGet(JsonNameTable nameTable)
        {
            Random r = new Random();

            const int Times = 10000;
            for (int i = 0; i < Times; ++i)
            {
                int index = r.Next(0, randomStrings.Length);
                char[] chars = randomStrings[index].ToArray();
                nameTable.Get(chars, 0, chars.Length);
            }
        }

        static void RunAdd(DefaultJsonNameTable nameTable)
        {
            for (int i = 0; i < randomStrings.Length; ++i)
            {
                lock (nameTable)
                {
                    nameTable.Add(randomStrings[i]);
                }
            }
        }

        static string RandomString(int length)
        {
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            return new string(Enumerable.Repeat(chars, length)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }
    }
}
```

The program uses Newtonsoft.Json 13.0.1 and built using .Net 5.
The program didn't crash on my PC(with x64 cpu), but crashed on Raspberry Pi(with ARM cpu).
Here is the output:
```
CPU Arch: Arm, Processor count: 4
100
200
...
2000
2100
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Newtonsoft.Json.DefaultJsonNameTable.Get(Char[] key, Int32 start, Int32 length)
   at TestJson.Program.RunGet(JsonNameTable nameTable) in D:\Projects\TestJson\Program.cs:line 59
   at TestJson.Program.<>c__DisplayClass2_0.<Main>b__1(Object x) in D:\Projects\TestJson\Program.cs:line 30
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

```

I think the issue is due to the weaker memory model of ARM cpu (hardware can reorder instructions).
I tried to make some changes of DefaultJsonNameTable, the program dosen't crash anymore:
```csharp
public override string? Get(char[] key, int start, int length)
{
	// ...

	// make sure index is evaluated before accessing _entries, otherwise potential race condition causing IndexOutOfRangeException
	// var index = hashCode & _mask;
        var index = hashCode & Volatile.Read(ref _mask);          // <<------------
	var entries = _entries;

	// ...
}

private void Grow()
{
	// ...
	_entries = newEntries;
	// _mask = newMask;
       Volatile.Write(ref _mask, newMask);            // <<------------
}
```

In older .NET Framework where Volatile.Read/Write dose not exist, Thread.VolatileRead/Write can be used as an alternative.

**Comment by AlanLiu90** [comment]
Reference: https://docs.microsoft.com/en-us/archive/msdn-magazine/2013/january/csharp-the-csharp-memory-model-in-theory-and-practice-part-2
