### ISSUE TITLE
Get error Could not load file or assembly 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral

### ISSUE THREAD

**Issue by xenicle** [JamesNK/Newtonsoft.Json#2621]
I getting ```
[05:27:06] Failed loading dump: System.IO.FileNotFoundException: Could not load file or assembly 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

File name: 'System.Security.Permissions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Newtonsoft.Json.Serialization.JsonTypeReflector.get_DynamicCodeGeneration()
   at Newtonsoft.Json.Serialization.JsonTypeReflector.get_ReflectionDelegateFactory()
   at Newtonsoft.Json.Serialization.DefaultContractResolver.GetDefaultCreator(Type createdType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(JsonContract contract)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateArrayContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at PedSyncer.Utils.FileControl.LoadDataFromJsonFile[TDumpType](String dumpFileName)
[05:27:06] < ==== UNHANDLED EXCEPTION ==== >
 Received an unhandled exception from : System.NullReferenceException: Object reference not set to an instance of an object.
   at PedSyncer.Control.StreetCrossingControl..ctor()
   at PedSyncer.Control.StreetCrossingControl.getInstance()
   at PedSyncer.PedSyncer.OnStart()
[05:27:06] < ==== UNHANDLED EXCEPTION ==== >
 Received an unhandled exception from : System.NullReferenceException: Object reference not set to an instance of an object.
   at PedSyncer.Control.StreetCrossingControl..ctor()
   at PedSyncer.Control.StreetCrossingControl.getInstance()
   at PedSyncer.PedSyncer.OnStart()
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at PedSyncer.Control.StreetCrossingControl..ctor()
   at PedSyncer.Control.StreetCrossingControl.getInstance()
   at PedSyncer.PedSyncer.OnStart()
Abandon (core dumped)
```
With my project on Net core 5.0
No matter I have tried on Visual Studio...

**Comment by elgonzo** [comment]
You are using the wrong Newtonsoft.Json library variant.

The Newtonsoft.Json library comes in variants for .NET Standard 2.0, the older .NET Famework 2, .NET Famework  3.5, .NET Famework 4, .NET Famework 4.5, and for some other framework targets.

The library trying to use `System.Security.Permissions` is an indication that you use the Newtonsoft.Json library variant for .NET Framework 4.5 or older. Which is not the correct variant if your project targets .NET Core or .NET 5.

To fix your problem, make sure your project is using the Newtonsoft.Json library variant for **.NET Standard 2.0**.

**Comment by xenicle** [comment]
Thanks a lot : using .NET Standard 2.0 variant fixed it !
