### ISSUE TITLE
Deserializer deserializes into objects based on their name before their JsonProperty attribute

### ISSUE THREAD

**Issue by GNUGradyn** [JamesNK/Newtonsoft.Json#2680]
When deserializing onto a type that contains both an object with a name matching a json property and a `JsonProperty` matching the json property, the deserializer attempts to deserialize it onto the object

### Source/destination types

```csharp
public class DemoObject {
	[JsonProperty("DemoProperty")]
	private int _DemoProperty;
	public DateTimeOffset DemoProperty { get { return DateTimeOffset.FromUnixTimeSeconds(Convert.ToInt64(_DemoProperty)); } }
}
```

### Source/destination JSON

```javascript
{"DemoProperty": 0}
```

### Expected behavior

DemoProperty should be deserialized onto the _DemoProperty int, despite the fact there is an actual object called DemoProperty already.

### Actual behavior

An exception occurs
```
Unhandled exception. Newtonsoft.Json.JsonSerializationException: A member with the name 'DemoProperty' already exists on 'DemoObject'. Use the JsonPropertyAttribute to specify another name.
   at Newtonsoft.Json.Serialization.JsonPropertyCollection.AddProperty(JsonProperty property)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperties(Type type, MemberSerialization memberSerialization)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get(TKey key)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.GetContractSafe(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Program.Main()
Command terminated by signal 6
```

### Steps to reproduce

```csharp
using Newtonsoft.Json;
using System;
					
public class Program
{
	public static void Main()
	{
		Console.WriteLine("Hello World");
		JsonConvert.DeserializeObject<DemoObject>("{'DemoProperty': 0}");
	}
}

public class DemoObject {
	[JsonProperty("DemoProperty")]
	private int _DemoProperty;
	public DateTimeOffset DemoProperty { get { return DateTimeOffset.FromUnixTimeSeconds(Convert.ToInt64(_DemoProperty)); } }
}
```
This should not cause an exception if it's working properly

**Comment by TylerBrinkley** [comment]
Try putting a `[JsonIgnore]` attribute on the `DemoProperty`.

**Comment by GNUGradyn** [comment]
This is a good workaround, but JsonProperty should still probably take priority over object names
