### ISSUE TITLE
Cannot Serialise a F# Map<int option, string>

### ISSUE THREAD

**Issue by thatstatsguy** [JamesNK/Newtonsoft.Json#2746]
Hi - I'm currently trying to serialise an F# Map where the key is an option. 

Serialising the object results in a null reference exception. Example code below

### Expected behavior
Some kind of serialization result.

### Actual behavior
The following null reference exception.
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetPropertyName(JsonWriter writer, Object name, JsonContract contract, Boolean& escape)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value)
```

### Steps to reproduce
Serialization fails even if the null handling setting is used. Two examples are given below.

```
let testDictionary : Map<int option,string> = [|(None, "test"); ((Some 1), "test2")|]|> Map.ofArray

let testSerialisation = JsonConvert.SerializeObject testDictionary
            
let settings = new JsonSerializerSettings()
settings.NullValueHandling <- NullValueHandling.Ignore
            
let testSerialisation2 = JsonConvert.SerializeObject (testDictionary, settings)
```

**Comment by bartelink** [comment]
Might make sense to see whether FsCodec.NewtonsoftJson covers this case (and, if not, whether it's possible to tweak it's OptionConverter to make it do what you want). Wild guess says this is not about Option, but about null handling in general.

IIRC there are lots of edge cases with the handling of Keys for Maps and/or Dictionary types (search StackOverflow), and that's before you even get into nullable/optional ones (can you use another sentinel value for `None` to work around this?)

Have you tried using `Nullable<int>` instead? Does it work in `System.Text.Json` (it has pretty complete and tested F# support as of recent versions) ? (It's also worth pointing out that maintainer activity in this repo has dropped off significantly in recent times, so I'd be looking for workarounds before attempting a PR to fix it if you truly need this.
