### ISSUE TITLE
Cannot serialize F# struct with dotnet 7 SDK 

### ISSUE THREAD

**Issue by nojaf** [JamesNK/Newtonsoft.Json#2758]
### Source/destination types

```csharp
    public struct CRange
    {
        public int StartLine { get; }
        public int StartColumn { get; }
        public int EndLine { get; }
        public int EndColumn { get; }

        public CRange(int startLine, int startColumn, int endLine, int endColumn)
        {
            StartLine = startLine;
            StartColumn = startColumn;
            EndLine = endLine;
            EndColumn = endColumn;
        }
    }
```

```fsharp
type FRange =
    struct
        val StartLine: int
        val StartColumn: int
        val EndLine: int
        val EndColumn: int

        new(startLine: int, startColumn: int, endLine: int, endColumn: int) =
            { StartLine = startLine
              StartColumn = startColumn
              EndLine = endLine
              EndColumn = endColumn }
    end
```

### Source/destination JSON

```javascript
{"startLine":0,
 "startColumn": 0,
 "endLine": 0,
 "endColumn": 0 }
```

### Expected behavior

Hello, to my surprise serializing the F# struct no longer works with the dotnet 7 SDK.
The exact same code works with `6.0.400` but not with `7.0.100`.

### Actual behavior

```
Failed serialize F# struct [9 ms]
Error Message:
System.IO.FileNotFoundException : Could not load file or assembly '"The system type 'System.Runtime.CompilerServices.IsReadOnlyAttribute' was required but no referenced system DLL contained this type", Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Stack Trace:
at System.ModuleHandle.ResolveType(QCallModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
at System.ModuleHandle.ResolveTypeHandle(Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(MetadataToken caCtorToken, MetadataImport& scope, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes, RuntimeType& attributeType, IRuntim
eMethodInfo& ctorWithParameters, Boolean& isVarArg)
at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Int32 attributeCtorToken, Boolean mustBeInheritable)
at System.Reflection.CustomAttribute.IsDefined(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
at System.Reflection.RuntimeMethodInfo.IsDefined(Type attributeType, Boolean inherit)
at Newtonsoft.Json.Serialization.DefaultContractResolver.IsValidCallback(MethodInfo method, ParameterInfo[] parameters, Type attributeType, MethodInfo currentCallback, Type& prevAttributeType)
at Newtonsoft.Json.Serialization.DefaultContractResolver.GetCallbackMethodsForType(Type type, List`1& onSerializing, List`1& onSerialized, List`1& onDeserializing, List`1& onDeserialized, List`1& onError)
at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveCallbackMethods(JsonContract contract, Type t)
at Newtonsoft.Json.Serialization.DefaultContractResolver.InitializeContract(JsonContract contract)
at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
at Newtonsoft.Json.Utilities.ThreadSafeStore`2.Get(TKey key)
at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContract(Object value)
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContractSafe(Object value)
at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, JsonSerializerSettings settings)
at Newtonsoft.Json.JsonConvert.SerializeObject(Object value)
```

### Steps to reproduce

I made a sample over at https://github.com/nojaf/serialize-struct.
I'm not sure if this is a problem in this repository, as it does in both scenarios work for the C# struct.

@vzarytovskii could this be a regression in the F# compiler? The compiled binary is slightly different with the new SDK and this leads to funny business at runtime?

**Comment by nojaf** [comment]
@vzarytovskii I do see a difference when opening the compiled assemblies in dotPeek:

*6.0.400*:
![image](https://user-images.githubusercontent.com/2621499/200805943-ba9fd9db-88bd-43cb-a4f7-cf48171a6767.png)

*7.0.100*:
![7 0 100](https://user-images.githubusercontent.com/2621499/200805965-68f1e11d-4e5c-4f05-90cd-c6fff4558e3f.png)

**Comment by vzarytovskii** [comment]
Yes, it seems `IsReadOnlyAttribute` is not available in netstandard2.0, we should check the target framework when we emitting it.

**Comment by nojaf** [comment]
Thanks for confirming, nothing left to do here.
