### ISSUE TITLE
JToken.Parse can't deserialize BigInteger

### ISSUE THREAD

**Issue by aliveli186** [JamesNK/Newtonsoft.Json#2791]
Newtonsoft.Json 13.0.2"            

### Source/destination types

```csharp
BigInteger
```

### Source/destination JSON

```javascript
{"logsBloom":9862442992560025030252661728793228559780952006488160418307588385383011236981140545031805882715837028005470074369207419038885345704095359761817407269384081172617220255058343853004368242738150972884466293420969034463720629904583335554958487959354254463517863066529516260224975466870248866666031182139906421401044885679543966062744782706988028182016913165699755407007459890998811818520339308542092646494713463582978860368687026141384751107498202494188684617402453231810619845493362533290262659599215199039789361399065829404782152245922097818694141460744794917794296590195956331008249111048065437990368352739656816787488}
```

### Expected behavior

Should be able to deserialize as BigInteger or string.

### Actual behavior

```
Newtonsoft.Json.JsonReaderException
  HResult=0x80131500
  Message=JSON integer 9862442992560025030252661728793228559780952006488160418307588385383011236981140545031805882715837028005470074369207419038885345704095359761817407269384081172617220255058343853004368242738150972884466293420969034463720629904583335554958487959354254463517863066529516260224975466870248866666031182139906421401044885679543966062744782706988028182016913165699755407007459890998811818520339308542092646494713463582978860368687026141384751107498202494188684617402453231810619845493362533290262659599215199039789361399065829404782152245922097818694141460744794917794296590195956331008249111048065437990368352739656816787488 is too large to parse. Path 'logsBloom', line 1, position 629.
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json)
```

### Steps to reproduce

```csharp
var logsBloom = "{\"logsBloom\":9862442992560025030252661728793228559780952006488160418307588385383011236981140545031805882715837028005470074369207419038885345704095359761817407269384081172617220255058343853004368242738150972884466293420969034463720629904583335554958487959354254463517863066529516260224975466870248866666031182139906421401044885679543966062744782706988028182016913165699755407007459890998811818520339308542092646494713463582978860368687026141384751107498202494188684617402453231810619845493362533290262659599215199039789361399065829404782152245922097818694141460744794917794296590195956331008249111048065437990368352739656816787488}";
var token     = JToken.Parse(logsBloom);
```

**Comment by elgonzo** [comment]
This harks back to a [commit made in 2014](https://github.com/JamesNK/Newtonsoft.Json/pull/287/files#diff-188cdcd35a8220c2477c864944a945fa67539c0beac51d3909424ff07dea7fe4), limiting the number parsing to the maximum length in characters/digits Javascript could handle.

What i don't get at all is why this limitation has been applied to the JsonTextReader. JsonTextReader is not producing any json at all, hence JsonTextReader being able to parse big integers longer than _MaximumJavascriptIntegerLengthInCharacters_ would not endanger any Javascript script or engine.

It would have made some sense to put such a limitation on to JsonTextWriter as it produces json, but (plot twist!) JsonTextWriter has no such limitation. Proof: https://dotnetfiddle.net/U7qEPF

I can't see no sense nor rhyme behind accepting that commit, and i am in favour of undoing it in an upcoming Newtonsoft.Json release.

**Comment by JamesNK** [comment]
Parsing extremely large big integer values causes the parser to slow down exponentially. Limiting the size was a security fix.

**Comment by elgonzo** [comment]
> Parsing extremely large big integer values causes the parser to slow down exponentially. Limiting the size was a security fix.

Thanks for the clarification!

**Comment by aliveli186** [comment]
> Parsing extremely large big integer values causes the parser to slow down exponentially. Limiting the size was a security fix.

If it's too long, it can be treated as a string instead of throwing an exception!
Blockchain development requires to work with such big integers all the time, maybe you should reconsider your decision.

**Comment by JamesNK** [comment]
What do you mean by treat it as a string? The deserializer is converting it to a `BigInteger` because the property is presumably a `BigInteger`.

If you want the value as a string then you can do that today by making the property type a string:

```cs
using System;
using Newtonsoft.Json;
					
public class Program
{
	public static void Main()
	{
		var s = @"{""logsBloom"":9862442992560025030252661728793228559780952006488160418307588385383011236981140545031805882715837028005470074369207419038885345704095359761817407269384081172617220255058343853004368242738150972884466293420969034463720629904583335554958487959354254463517863066529516260224975466870248866666031182139906421401044885679543966062744782706988028182016913165699755407007459890998811818520339308542092646494713463582978860368687026141384751107498202494188684617402453231810619845493362533290262659599215199039789361399065829404782152245922097818694141460744794917794296590195956331008249111048065437990368352739656816787488}";

		var c = JsonConvert.DeserializeObject<TestClass>(s);
		Console.WriteLine(c.LogsBloom);
	}
	
	public class TestClass
	{
		public string LogsBloom { get; set; }
	}
}
```

**Comment by aliveli186** [comment]
```
var c = JsonConvert.DeserializeObject<TestClass>(s);
Console.WriteLine(c.LogsBloom);

public class TestClass
{
  public string LogsBloom { get; set; }
}
```
This approach doesn't suit my design!
I have a socket connection that receives different kinds of json string responses. Those responses are first converted to JToken object by "JToken.Parse" and filtered according to some properties and later are converted to objects of known types (TestClass).
Because "JToken.Parse" throws and exception the message doesn't propagate to the outer layers.
It should not throw exception if it thinks it is integer and above some certain size. If it is not designed to convert it to BigInteger it needs to threat is as string to allow the user to handle the BigInteger conversion at least

**Comment by BuslikDrev** [comment]
Эта дичь! В итоге нужно добавить в код костыль для поиска таких чисел и помещения их в кавычки.
```
var s = @"{""logsBloom"":""9862442992560025030252661728793228559780952006488160418307588385383011236981140545031805882715837028005470074369207419038885345704095359761817407269384081172617220255058343853004368242738150972884466293420969034463720629904583335554958487959354254463517863066529516260224975466870248866666031182139906421401044885679543966062744782706988028182016913165699755407007459890998811818520339308542092646494713463582978860368687026141384751107498202494188684617402453231810619845493362533290262659599215199039789361399065829404782152245922097818694141460744794917794296590195956331008249111048065437990368352739656816787488}""";
```
