### ISSUE TITLE
Newtonsoft.Json 13.0.3 NuGet fails to install to .NET Framework 4.8 projects

### ISSUE THREAD

**Issue by jdfurlan** [JamesNK/Newtonsoft.Json#2897]
### Expected behavior
Newtonsoft.Json 13.0.3 NuGet installs cleanly with no errors.

### Actual behavior
Package Manager output shows the below:
```
Attempting to gather dependency information for package 'Newtonsoft.Json.13.0.3' with respect to project 'ConsoleApp1', targeting '.NETFramework,Version=v4.8'
Gathering dependency information took 62 ms
Attempting to resolve dependencies for package 'Newtonsoft.Json.13.0.3' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Newtonsoft.Json.13.0.3'
Resolved actions to install package 'Newtonsoft.Json.13.0.3'
Adding package 'Newtonsoft.Json.13.0.3' to folder 'C:\Users\dev.CLOUDDEV\source\repos\ConsoleApp1\packages'
Install failed. Rolling back...
Package 'Newtonsoft.Json.13.0.3' does not exist in project 'ConsoleApp1'
Package 'Newtonsoft.Json.13.0.3' does not exist in folder 'C:\Users\dev.CLOUDDEV\source\repos\ConsoleApp1\packages'
Executing nuget actions took 714 ms
System.UnauthorizedAccessException: Access to the path 'C:\Users\dev.CLOUDDEV\source\repos\ConsoleApp1\packages\Newtonsoft.Json.13.0.3\.signature.p7s' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
   at System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
   at NuGet.Packaging.ZipArchiveExtensions.Testable.UpdateFileTimeEntry(String fileFullPath, DateTime dateTime)
   at NuGet.Packaging.PackageFolderReader.CopyFiles(String destination, IEnumerable`1 packageFiles, ExtractPackageFileDelegate extractFile, ILogger logger, CancellationToken token)
   at NuGet.Packaging.PackageReaderBase.CopyFilesAsync(String destination, IEnumerable`1 packageFiles, ExtractPackageFileDelegate extractFile, ILogger logger, CancellationToken cancellationToken)
   at NuGet.Packaging.PackageExtractor.<ExtractPackageAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.ProjectManagement.FolderNuGetProject.<>c__DisplayClass13_0.<<InstallPackageAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.ProjectManagement.MSBuildNuGetProject.<InstallPackageAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteInstallAsync>d__97.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__85.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__84.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.NuGetProjectManagerService.<>c__DisplayClass20_0.<<ExecuteActionsAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.VisualStudio.NuGetProjectManagerService.<CatchAndRethrowExceptionAsync>d__32.MoveNext()
Time Elapsed: 00:00:01.8687560
========== Finished ==========
```
### Steps to reproduce
- Create a brand new .NET Framework 4.8 project.
- Attempt to install Newtonsoft.Json 13.0.3 NuGet to the project

### Notes
- I haven't tested this with other versions of .NET Framework
- I have tested this with .NET 6+ projects, and it works fine
- From what I can tell, the .signature.p7s file that is part of this NuGet (for framework only) is marked as Read-only:
![image](https://github.com/JamesNK/Newtonsoft.Json/assets/11356304/4c3de4fd-ab47-4fa9-a806-b9680b22b163)
- After inspecting older Newtonsoft.json packages (v 13.0.1), I've confirmed that signature file isn't marked as Read-only during installation
- Suspect that the fact the file .signature.p7s is marked as Read-only in the NuGet itself (for framework only) is what is causing the `Access to the path is denied` exception

**Comment by jdfurlan** [comment]
Confirmed that an old version of the nuget was sitting in my packages folder. After deleting, it installed correctly. Somehow the signature file set as read-only. Thanks for looking.
