### ISSUE TITLE
Can't deserialized object just serialized.

### ISSUE THREAD

**Issue by PaulStSmith** [JamesNK/Newtonsoft.Json#2911]
At some moment in my code, I had to do a variation of this:

```
class Foo
{
    public readonly IList<Bar> MyProperty = new List<Bar>();
}

store = JsonConvert.DeserializeObject<Foo>(JsonConvert.SerializeObjct(new Foo()));
```

Then I get the following exception:
```
Error converting value "Foo" to type 'Foo'. Path '', line 1, position 42.
```

Which in turn had the following source:
```
Could not cast or convert from System.String to Foo.
```

Debugging the serialized string it had the value `"Foo"` instead of the expected:

```
{
  MyProperty : []
}
```

----
StackTrace for the first Exception:
```
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at MyCode . . . 
```

StackTrace for the InnerException:
```
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
```

**Comment by elgonzo** [comment]
Not reproducible.

Please make sure that the example code you include in your report actually demonstrates the issue you are reporting.

If you have verified that the code in your report does indeed exhibit the behavior you are reporting about, please first make sure you are using the most recent version of Newtonsoft.Json.

If the problem still occurs with the most recent version of Newtonsoft.Json and with the code in your report, then provide details about build setting and the environment in which you are running the code, such as but not limited to:
 - .NET version your program is targeting
 - Build settings that have an impact on output the compiler produces (such as settings that govern code trimming or native AOT compiling)
 - the runtime environment (.NET runtime, Mono, Xamarin, iOS, etc) the program is being executed in

**Comment by BuslikDrev** [comment]
Может readonly не позволяет?
