### ISSUE TITLE
Deserialization exception

### ISSUE THREAD

**Issue by sunyuliang** [JamesNK/Newtonsoft.Json#2986]
Input string '0355264698' is not a valid number. Path 'Time', line 1, position 151.
Newtonsoft.Json.JsonReaderException: Input string '0355264698' is not a valid number. Path 'Time', line 1, position 151.
 ---> System.FormatException: Additional non-parsable characters are at the end of the string.
   at System.ParseNumbers.StringToLong(ReadOnlySpan`1 s, Int32 radix, Int32 flags, Int32& currPos)
   at System.Convert.ToInt64(String value, Int32 fromBase)
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)

### Source/destination types

```csharp
JsonConvert.DeserializeObject<Dictionary<string, object>>(str);
```

### Source/destination JSON

```javascript
{"DeviceCode":"PESO0230","ProductCode":"resistance","DATE":"19810405075902","NUM":"33596","R1":"7.046000","R2":"0.000000","LEN":"0.0","Time":0355264698}
```

### Steps to reproduce

```csharp
// Your calls to Newtonsoft.Json here
```

**Comment by elgonzo** [comment]
> Input string '0355264698'

The error is correct. The json format does NOT allow leading zeros except a single zero in front of a decimal point.
Hence, the value for the "Time" property in your example json you displayed is not legal json to begin with.

**Comment by majid3ma** [comment]
The JSON you provided is invalid. Please check the element of time, it should be in double quotes like this below.
`{"DeviceCode":"PESO0230","ProductCode":"resistance","DATE":"19810405075902","NUM":"33596","R1":"7.046000","R2":"0.000000","LEN":"0.0","Time":"0355264698"}
`
