### ISSUE TITLE
The Newtonsoft.Json.dll signing certificate is expired

### ISSUE THREAD

**Issue by Petr-Kovalev** [JamesNK/Newtonsoft.Json#2998]
The Newtonsoft.Json.dll signing certificate is expired. Vaild to Tuesday, October 29, 2024 11:59:59 PM

<img width="404" alt="Certificate" src="https://github.com/user-attachments/assets/fba7a819-d6a8-41b8-bb3e-79aaa815cb62">

**Comment by JamesNK** [comment]
Does this cause a problem?

**Comment by Petr-Kovalev** [comment]
Hello James!

We got this stack trace in one of our products on a call to JsonConvert.SerializeObject(). I assume the certificate is the root cause.
I've added Newtonsoft.Json.dll assembly signing with our own certificate as a workaround. But decided to let you know. Someone else might have a similar issue.

```
Application: Workplace Container Helper.exe
CoreCLR Version: 8.0.1024.46610
.NET Version: 8.0.10
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: Could not load file or assembly 'C:\Program Files (x86)\Workplace\Components\WorkplaceContainerComponent\Current\Newtonsoft.Json.dll'. Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source. (0x80070241)
File name: 'C:\Program Files (x86)\Workplace\Components\WorkplaceContainerComponent\Current\Newtonsoft.Json.dll'
   at Workplace.Logger.Formatters.FileLogFormatter.Format(IDetailedLogEvent logEvent)
   at Workplace.Logger.Writers.Rolling.RollingFileLogWriter.DequeueLogMessages()
   at Workplace.Logger.Writers.Rolling.RollingFileLogWriter.Flush()
   at Workplace.Logger.Logger.Flush()
   at Workplace.Logger.LoggerManager.Flush()
   at Workplace.Container.Api.Common.Logger.WorkplaceLogger.WorkplaceLoggerConfig.FlushLogs()
   at Workplace.Container.Helper.ContainerHelperRunner.<>c__DisplayClass4_0.<RunAsync>b__0()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Workplace.Container.Helper.Application.Main(String[] args)
   at Workplace.Container.Helper.Application.<Main>(String[] args)
```

**Comment by Petr-Kovalev** [comment]
Important note, it was reproduced on Windows 11 24H2, not reproduced on Windows 10

**Comment by Petr-Kovalev** [comment]
Find out that the issue was actually caused by a call of [SetProcessMitigationPolicy](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setprocessmitigationpolicy) with enabled flag MicrosoftSignedOnly in [PROCESS_MITIGATION_BINARY_SIGNATURE_POLICY](https://learn.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-process_mitigation_binary_signature_policy).

So there is no issue with the current Newtonsoft.Json.dll signature.
