### ISSUE TITLE
Consider accounting for targetType of Version in TryConvertInternal of ConvertUtils.cs

### ISSUE THREAD

**Issue by manastalukdar** [JamesNK/Newtonsoft.Json#426]
In ConvertUtils.cs, in method "private static ConvertResult TryConvertInternal(object initialValue, CultureInfo culture, Type targetType, out object value)", targetType of Version is not accounted for.

As a result, we get following JsonSerializationException:

Newtonsoft.Json.JsonSerializationException: Error converting value \"1.0.2.0\" to type 'System.Version'. Path 'Value', line 1, position 63. ---> System.ArgumentException: Could not cast or convert from System.String to System.Version.
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)

Please consider adding the following to mitigate this error:

if (targetType == typeof(Version))
    {
        Version result;
        string input = initialValue.ToString();
        Version.TryParse(input, out result);
        value = result;
        return ConvertResult.Success;
    }

**Comment by JamesNK** [comment]
Done https://github.com/JamesNK/Newtonsoft.Json/commit/57f4f9816204230bdb2fc356c497f993bf25d86f
