### ISSUE TITLE
Issue deserializing DateTimeOffset

### ISSUE THREAD

**Issue by niemyjski** [JamesNK/Newtonsoft.Json#497]
I have the following property on my [event](https://github.com/exceptionless/Exceptionless/blob/master/Source/Core/Models/Event.cs):

        public DateTimeOffset Date { get; set; }

and I'm trying to deserialize [this file](https://github.com/exceptionless/Exceptionless/blob/master/Source/Api.Tests/Search/Data/event1.json) with default datetime handling settings:

      "date": "2015-02-11T20:54:04.3457274+00:00",

However, json.net is treating this as a DateTime and not a DateTimeOffset..

![image](https://cloud.githubusercontent.com/assets/1020579/6444579/1b146b0e-c0c4-11e4-9a53-ce5f04b5e841.png)

Thus I can't serialize and deserialize the same file without my data changing!!!

**Comment by niemyjski** [comment]
When I set the DateParseHandling = DateParseHandling.DateTimeOffset I get a crazy exception. I think this is caused when it tries to deserialize a normal date time.

	System.InvalidCastException was caught
	  _HResult=-2147467262
	  _message=Specified cast is not valid.
	  HResult=-2147467262
	  IsTransient=false
	  Message=Specified cast is not valid.
	  Source=Newtonsoft.Json
	  StackTrace:
		   at Newtonsoft.Json.JsonReader.ReadAsDateTimeInternal()
		   at Newtonsoft.Json.Linq.JTokenReader.ReadAsDateTime()
		   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
		   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
		   at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
		   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
		   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
		   at Exceptionless.Serializer.DataObjectConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in c:\Code\Exceptionless\Source\Core\Serialization\DataObjectConverter.cs:line 52
		   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
		   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
		   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
		   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
		   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
		   at Exceptionless.Core.Extensions.JsonExtensions.FromJson[T](String data, JsonSerializerSettings settings) in c:\Code\Exceptionless\Source\Core\Extensions\JsonExtensions.cs:line 223
		   at Exceptionless.Core.Extensions.JsonExtensions.TryFromJson[T](String data, T& value, JsonSerializerSettings settings) in c:\Code\Exceptionless\Source\Core\Extensions\JsonExtensions.cs:line 228
	  InnerException:

**Comment by niemyjski** [comment]
When I serialize the read in object to disk, it serializes it with the -6 offset.

**Comment by niemyjski** [comment]
I added a test that shows this off  ( https://github.com/JamesNK/Newtonsoft.Json/pull/498 )

**Comment by JamesNK** [comment]
This happens because the reader has already read the string as a DateTime before it enters the converter. You could set DateParseHandling to DateParseHandling.DateTimeOffset.

**Comment by niemyjski** [comment]
Why not put that as the default and deserialize it to the correct type. Then you won't lose information... I made this change but had to correct our custom converter and am worried about issues I might not know about.

Sent from Outlook




On Sat, Mar 7, 2015 at 4:31 PM -0800, "James Newton-King" <notifications@github.com> wrote:












This happens because the reader has already read the string as a DateTime before it enters the converter. You could set DateParseHandling to DateParseHandling.DateTimeOffset.

**Comment by JamesNK** [comment]
Because it is a breaking change and tens of thousands of applications depend on the current behavour.

**Comment by niemyjski** [comment]
Yeah I get this, but still kind of sucks that information is lost.

Sent from Outlook




On Sat, Mar 7, 2015 at 4:53 PM -0800, "James Newton-King" <notifications@github.com> wrote:












Because it is a breaking change and tens of thousands of applications depend on the current behavour.
