### ISSUE TITLE
NullReferenceException when using readonly JObject JsonExtensionData properties

### ISSUE THREAD

**Issue by shannoncornish** [JamesNK/Newtonsoft.Json#508]
The SerializeObject method throws a NullReferenceException when trying to serialize an object with a read only JObject JsonExtensionData property.

```c#
    class Program
    {
        class DocContent
        {
            public string Title { get; set; }
        }

        class Doc
        {
            readonly object content;

            public Doc(object content)
            {
                this.content = content;
            }

            [JsonProperty("_name")]
            public string Name { get; set; }

            [JsonExtensionData]
            public JObject Content
            {
                get { return new JObject(content); }
            }
        }

        static void Main(string[] args)
        {
            var json = JsonConvert.SerializeObject(new Doc(new DocContent {Title = "contentTitle"}) {Name = "documentName"});
            Console.WriteLine(json);
        }
    }
  ```

Exception stack trace
```
   at Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.GenerateCreateSetPropertyIL(PropertyInfo propertyInfo, ILGenerator generator)
   at Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.CreateSet[T](PropertyInfo propertyInfo)
   at Newtonsoft.Json.Utilities.ReflectionDelegateFactory.CreateSet[T](MemberInfo memberInfo)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.SetExtensionDataDelegates(JsonObjectContract contract, MemberInfo member)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateObjectContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateContract(Type objectType)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetContractSafe(Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value)
   at Test.Program.Main(String[] args)
```

Changing the JsonExtensionData property to a read/write property works as expected.
```c#
    class Program
    {
        class DocContent
        {
            public string Title { get; set; }
        }

        class Doc
        {
            [JsonProperty("_name")]
            public string Name { get; set; }

            [JsonExtensionData]
            public JObject Content { get; set; }
        }

        static void Main(string[] args)
        {
            var jObject = JObject.FromObject(new DocContent { Title = "contentTitle" });
            var json = JsonConvert.SerializeObject(new Doc { Name = "documentName", Content = jObject });
            // no exceptions
            Console.WriteLine(json);
        }
    }
```

**Comment by JamesNK** [comment]
Fixed
