### ISSUE TITLE
Exception when deserializing a nullable IConvertible type with DefaultValueHandling.Populate

### ISSUE THREAD

**Issue by aj-r** [JamesNK/Newtonsoft.Json#520]
I have a struct that implements `IConvertible` (let's call it `MyStruct`). I also have a class that has a `Nullable<MyStruct>` property. If I set `DefaultValueHandling` to `DefaultValueHandling.Populate` and try to deserialize an instance of the class where the property is not set, then I get an exception.

Note that this also happens if you deserialize a string with the property set to null, but you can work around this by creating a custom JsonConverter. However, this workaround does not work with `DefaultValueHandling.Populate` because the converter never even gets called.

**Gist to reproduce the issue:**

 https://gist.github.com/aj-r/39b79672a9c5a5b55037

**Exception details:**

Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Nullable\`1[Sandbox.Program+MyStruct]'. Path '', line 1, position 2. ---> System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EndObject(Object newObject, JsonReader reader, JsonObjectContract contract, Int32 initialDepth, Dictionary`2 propertiesPresence)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Sandbox.Program.Main(String[] args) in c:\projects\Sandbox\Sandbox\Program.cs:line 25

**Comment by aj-r** [comment]
Never mind; I fixed the issue by applying the JsonObjectAttribute to the IConvertible struct.
