### ISSUE TITLE
Expression.Lambda throws "NullReferenceException"  Win10 desktop

### ISSUE THREAD

**Issue by quincycs** [JamesNK/Newtonsoft.Json#610]
We are writing a Win10 desktop app (universal app platform), and are encountering the "NullReferenceException" at any Expression.Lambda call.

Its pretty odd, where this exception only happens sometimes even though the json input is EXACTLY the same.  It makes us cry.  It's seemingly random, but at the same time seems to happen only on App startup.  If you delay any serialization for a few arbitrary seconds we are not able to reproduce the problem!  Super weird, kind of feels like a platform issue (of the win10 pre-release flavor) but I wanted to see if anyone else had an opinion.  

There were several Expression.Lambda's in "ExpressionReflectionDelegateFactory" they seemed to be the culprit.  

Here's an example:
LambdaExpression lambdaExpression = Expression.Lambda(typeof(ObjectConstructor<object>), callExpression, argsParameterExpression);

If you don't have the source connected, you'd get these type of errors:

Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in Newtonsoft.Json.dll
Additional information: Error getting value from 'Urls' on 'Models.EntitiesModel'.

Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in Newtonsoft.Json.dll
Additional information: Error setting value from 'Width' on 'Models.CardImage'.

Where the innerexception is a NullReferenceException ({"Object reference not set to an instance of an object."} Error getting value from 'Urls' on 'Models.EntitiesModel'.)

   at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CalculatePropertyDetails(JsonProperty property, JsonConverter& propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target, Boolean& useExistingValue, Object& currentValue, JsonContract& propertyContract, Boolean& gottenCurrentValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Common.Serialization.Deserialize[T](String json)

**Comment by JamesNK** [comment]
I have no idea.

**Comment by ljw1004** [comment]
@quincycs are you using VS2015 RC? Are you encountering this in Debug builds? Are you encountering it in Release builds? Any chance you could send me a zip of a repro project? lwischik at microsoft.com

**Comment by quincycs** [comment]
Hi Lucian. 

Thanks for your interest to help.  Yup I'm using the RC and this appears for the 069 and the 166 SDK on every OS build we have had. 
My team and I are in crunch mode til the end of the month.  But after that I can discuss with them to see if we can prioritize some work to make a reproduce project. 

On the good news front, I think we have a workaround, but it's a real odd one :).  I'll circle back with it though - we are going thru a QA cycle and we might find a way that the workaround breaks.

**Comment by quincycs** [comment]
Oh and yes it's in debug and release.

**Comment by JamesNK** [comment]
I'm assuming you two have worked it out.
