### ISSUE TITLE
JsonSerializerSettings.ReferenceResolver Isn't Fully Backwards Compatible

### ISSUE THREAD

**Issue by brantburnett** [JamesNK/Newtonsoft.Json#710]
Json.net 7.0 added the ReferenceResolverProvider to JsonSerializerSettings, and made ReferenceResolver obsolete.  However, the new implementation of ReferenceResolver is not 100% backwards compatible with old versions.

If a library using the 6.0 version is redirected to the 7.0 version by binding redirect, and this library sets ReferenceResolver = null, deserialization will fail with the following error:

```
Reference resolver cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonSerializer.set_ReferenceResolver(IReferenceResolver value)
   at Newtonsoft.Json.JsonSerializer.ApplySerializerSettings(JsonSerializer serializer, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonSerializer.CreateDefault(JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Couchbase.Core.Serialization.DefaultSerializer.Deserialize[T](Stream stream) in C:\Users\bburnett\Source\Repos\couchbase-net-client\Src\Couchbase\Core\Serialization\DefaultSerializer.cs:line 172
   at Couchbase.Linq.Proxies.DocumentProxyDataMapper.Map[T](Stream stream) in C:\Users\bburnett\Source\Repos\Linq2Couchbase\Src\Couchbase.Linq\Proxies\DocumentProxyDataMapper.cs:line 57
   at Couchbase.N1QL.QueryClient.ExecuteQuery[T](IQueryRequest queryRequest) in C:\Users\bburnett\Source\Repos\couchbase-net-client\Src\Couchbase\N1QL\QueryClient.cs:line 362
```

The previous behavior when this property was set to null was to not pass a ReferenceResolver to the JsonSerializer.

An example use case can be found here: https://github.com/brantburnett/couchbase-net-client/blob/extendeddeserialization/Src/Couchbase/Core/Serialization/DefaultSerializer.cs#L249.

In this case, a specific workaround is already put in place to avoid the issue.  The specific use case in question was cloning a JsonSerializerSettings object to a new instance so that some minor modifications could be made without affecting the original object.  If the original object had a null ReferenceResolver, this issue occurred.

**Comment by JamesNK** [comment]
Fixed
