### ISSUE TITLE
When pass a Simple.Data oject to serialize it getting NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by ashanvabs** [JamesNK/Newtonsoft.Json#717]
I'm using 7.0.0 version and I just try to serialize the Simple.Data object its give me NullReferenceException: Object reference not set to an instance of an object exception. could you please explain me what would be the issue and how to overcome this.

stack trace : 
{System.NullReferenceException: Object reference not set to an instance of an object.
   at Newtonsoft.Json.JsonWriter.CreateUnsupportedTypeException(JsonWriter writer, Object value)
   at Newtonsoft.Json.JsonWriter.WriteValue(JsonWriter writer, PrimitiveTypeCode typeCode, Object value)
   at Newtonsoft.Json.JsonWriter.WriteValue(JsonWriter writer, PrimitiveTypeCode typeCode, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializePrimitive(JsonWriter writer, Object value, JsonPrimitiveContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeDictionary(JsonWriter writer, IDictionary values, JsonDictionaryContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Vetserve.Arkivering.Arkivar.TimeDataSamler.Samle(Int32 timeid, Int32 klinikkid) in d:\vetserve\TT\arkiv1\vetserve-legacy-archiving\src\Vetserve.Arkivering.Arkivar\TimeDataSamler.cs:line 56
   at Vetserve.Arkivering.Arkivar.Arkivar.LagOppføring(String dataKilde, Int32 id, Int32 klinikkid, Int32 versjon, Int32 dataversjon, String årsak) in d:\vetserve\TT\arkiv1\vetserve-legacy-archiving\src\Vetserve.Arkivering.Arkivar\Arkivar.cs:line 36
   at Vetserve.Arkivering.Arkivar.Arkivar.Arkiver(Int32 id, Int32 klinikkid, Int32 versjon, String dataKilde, Int32 dataversjon, String årsak) in d:\vetserve\TT\arkiv1\vetserve-legacy-archiving\src\Vetserve.Arkivering.Arkivar\Arkivar.cs:line 29
   at Vetserve.Arkivering.Interop.Arkiv.Arkiver(Int32 id, Int32 klinikkid, Int32 brukernr, Int32 brukerklinikkid, Int32 versjon, String datakilde, Int32 dataversjon, String årsak) in d:\vetserve\TT\arkiv1\vetserve-legacy-archiving\src\Vetserve.Arkivering.Interop\Arkiv.cs:line 389
   at Vetserve.Arkivering.Interop.Arkiv.ArkiverTime(Int32 timeId, Int32 klinikkid, Int32 brukernr, Int32 brukerklinikkid, Int32 versjon, String årsak) in d:\vetserve\TT\arkiv1\vetserve-legacy-archiving\src\Vetserve.Arkivering.Interop\Arkiv.cs:line 258}

**Comment by JamesNK** [comment]
I have never used Simple.Data. Could you upload a repo?

**Comment by ashanvabs** [comment]
I fixed it by  casting Simple.Data objects to DTOs  ( normal C# objects) so after that it is working fine. But the problem is still there.

http://simplefx.org/simpledata/docs/index.html
I was using Simple.Data as my DB framework. So when i query through this it will give me Simple.Data.Records. When I'm passing this kind of object preiouse error occure..
Thank you very much for you concerns. I'm really appreciate it. If you hae any free time please fix this also it would be great. thanks your lib great.. :+1:

**Comment by JamesNK** [comment]
I'll reopen if someone else runs into this and adds a repo.
