### ISSUE TITLE
Failure to get JToken when working with dynamic

### ISSUE THREAD

**Issue by jeme** [JamesNK/Newtonsoft.Json#735]
Given the following two test cases:

```C#
    [TestFixture]
    public class DynamicBehaviorShouldMimicNormal
    {
        [Test]
        public void DynamicAccess_ToJToken_ShouldNotFail()
        {
            dynamic json = JObject.FromObject(new { uid = Guid.NewGuid() });
            Assert.That(() => { JToken token = json.uid; }, Throws.Nothing);
            // Fail
        }

        [Test]
        public void DynamicAccess_ToJTokenExplicit_ShouldNotFail()
        {
            dynamic json = JObject.FromObject(new { uid = Guid.NewGuid() });
            Assert.That(() => { JToken token = (JToken)json.uid; }, Throws.Nothing);
            // Fail
        }

        [Test]
        public void DynamicAccess_ToJTokenSafeCast_ShouldNotFail()
        {
            dynamic json = JObject.FromObject(new { uid = Guid.NewGuid() });
            Assert.That(() => { JToken token = json.uid as JToken; Assert.That(token, Is.Not.Null);}, Throws.Nothing);
            // Pass
        }

        [Test]
        public void IndexAccess_ToJToken_ShouldNotFail()
        {
            JObject json = JObject.FromObject(new { uid = Guid.NewGuid() });
            Assert.That(() => { JToken token = json["uid"]; }, Throws.Nothing);
            // Pass
        }
    }
```

I would expect none of them to fail, after all they are from an outside perspective, essentially doing the same thing.

However one of them fails with: Target type Newtonsoft.Json.Linq.JToken is not a value type or a non-abstract class.

After all, `json.uid.GetType() == JValue` which is assignable to JToken. It seems like it attempts to convert something that never needed conversion in the first place, as it hits:

```
   at Newtonsoft.Json.Utilities.ConvertUtils.Convert(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Linq.JValue.JValueDynamicProxy.TryConvert(JValue instance, ConvertBinder binder, Object& result)
```

At this point: https://github.com/JamesNK/Newtonsoft.Json/blob/master/Src/Newtonsoft.Json/Utilities/ConvertUtils.cs#L410

Wouldn't it be more appropriate to say `if (targetType.IsAssignableFrom(initialType))` ??

***Edit:*** further more... Safe casting works, yet regular cast does not... Added test case examples.

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/4c256e7afd46197a6e40127f77dff18e8f044b8c

**Comment by jeme** [comment]
Cheers!
