### ISSUE TITLE
Cannot deserialize objects with null DataSet/DataTable

### ISSUE THREAD

**Issue by skimmilk** [JamesNK/Newtonsoft.Json#757]
In v7.0.1, I cannot deserialize objects that have a DataSet member set to null using the default settings for JsonConvert.  Serializing an object that has a null DataSet member appears to work and produces a valid JSON string, but deserialzing that fails.

Here's an example class:

```
using System;
namespace TestJson
{
    class Program
    {
        public System.Data.DataSet DataSet { get; set; }
        public string DummyData { get; set; }
        public Program()
        {
            DataSet = null;
            DummyData = "dummy data";
        }

        static void Main(string[] args)
        {
            try
            {
                var serialized = Newtonsoft.Json.JsonConvert.SerializeObject(new Program());
                Console.WriteLine(serialized);
                var deserialized = Newtonsoft.Json.JsonConvert.DeserializeObject<Program>(serialized);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Should not happen");
                Console.WriteLine(ex.ToString());
                Console.ReadLine();
                return;
            }
            Console.WriteLine("This is expected");
            Console.ReadLine();
        }
    }
}

```
```
{"DataSet":null,"DummyData":"dummy data"}
Should not happen
Newtonsoft.Json.JsonSerializationException: Unexpected JSON token when reading DataTable. Expected StartArray, got String. Path 'DummyData', line 1, position 40.
   at Newtonsoft.Json.Converters.DataTableConverter.ReadJson(JsonReader reader,Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Converters.DataSetConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContractcontainerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
```

**Comment by JamesNK** [comment]
That's already been fixed. It will be in the next release.

**Comment by Zarium** [comment]
Does not work in 12.0.1
