### ISSUE TITLE
Deserializing a Boolean Value to String Property works in 6.0.8 but breaks in 8.0.1

### ISSUE THREAD

**Issue by radleta** [JamesNK/Newtonsoft.Json#781]
I've run into a problem with upgrading from Newtonsoft.Json 6.0.8 to Newtonsoft 8.0.1.

The below works find using the Newtonsoft.Json 6.0.8 nuget package. There are no errors in the deserialization. However, when I update the nuget to Newtonsoft.Json 8.0.1 the below errors on the second attempt of deserialization.

Is this break of support suppose to happen with the new version? What is the best way to fix? Any ideas or suggestions?

```C#
namespace NewtonsoftJsonParseBooleanError
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;

    class Program
    {        
        public class MyObject
        {
            public string Value { get; set; }
        }
        
        static void Main(string[] args)
        {
            var value = Newtonsoft.Json.JsonConvert.DeserializeObject<MyObject>("{ \"Value\": \"true\" }");
            Console.WriteLine("Value: {0}", value.Value);
            // BUG: 8.0.1 throws an exception with the below attempt to deserialize the object.
            value = Newtonsoft.Json.JsonConvert.DeserializeObject<MyObject>("{ \"Value\": true }");
            Console.WriteLine("Value: {0}", value.Value);
            Console.ReadKey();
        }
    }
}
```

```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: t. Path 'Value', line 1, position 12.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at NewtonsoftJsonParseBooleanError.Program.Main(String[] args) in c:\Users\...\Projects\NewtonsoftJsonParseBooleanError\NewtonsoftJsonParseBooleanError\Program.cs:line 23
```

**Comment by JamesNK** [comment]
https://github.com/JamesNK/Newtonsoft.Json/issues/775

**Comment by JamesNK** [comment]
https://www.nuget.org/packages/Newtonsoft.Json/8.0.2

**Comment by radleta** [comment]
@JamesNK Thank you!

**Comment by rliberoff** [comment]
Is there a way to turn this off, so if the JSON sends a boolean value but the corresponding property is a string it throws an exception?
