### ISSUE TITLE
Cannot deserialize a XmlException

### ISSUE THREAD

**Issue by fvilers** [JamesNK/Newtonsoft.Json#801]
This sample code:

	var json = JsonConvert.SerializeObject(new XmlException("bla"));
	var exception = JsonConvert.DeserializeObject<XmlException>(json);

throws an InvalidCastException in Newtonsoft.Json.dll: Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'System.String' with the following stack trace:

	at System.Xml.XmlException..ctor(SerializationInfo info, StreamingContext context)
	at Void .ctor(System.Runtime.Serialization.SerializationInfo, System.Runtime.Serialization.StreamingContext)(Object[] )
	at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializable(JsonReader reader, JsonISerializableContract contract, JsonProperty member, String id)
	at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
	at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
	at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
	at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
	at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
	at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
	at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
	at TestJson.Program.Main(String[] args) in C:\Projects\TestJson\TestJson\Program.cs:line 21
	at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
	at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
	at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
	at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
	at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
	at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
	at System.Threading.ThreadHelper.ThreadStart()

**Comment by dbc2** [comment]
There is some analysis of the problem here: 

https://stackoverflow.com/questions/35015357/how-to-deserialize-a-xmlexception-with-newtonsoft-json/35023491#35023491

**Comment by JamesNK** [comment]
You will have to write a JsonConverter for it.

**Comment by knocte** [comment]
@JamesNK by any chance you know if System.Text.Json supports this OOTB, or does it also need converters?

**Comment by knocte** [comment]
Replying to myself: https://github.com/dotnet/runtime/issues/43026 (HTH someone)
