### ISSUE TITLE
[8.0.2] Failure to deserialize ulong on 1.0.0-rc1-update1 coreclr x64 win

### ISSUE THREAD

**Issue by highlyunavailable** [JamesNK/Newtonsoft.Json#838]
I'm trying to deserialize output from [Consul](https://www.consul.io/)'s JSON API into an array of this class:
```csharp
    public class KVPair
    {
        public string Key { get; set; }

        [JsonProperty]
        public ulong CreateIndex { get; private set; }

        [JsonProperty]
        public ulong ModifyIndex { get; set; }

        [JsonProperty]
        public ulong LockIndex { get; private set; }

        public ulong Flags { get; set; }
        public byte[] Value { get; set; }
        public string Session { get; set; }
    }
```

The `Flags` value is `0xe0f69a2baa414de0` in this case, and it only fails for the dnxcore50 (64-bit DNXCore 5.0) target, not dnx451 (64-bit DNX 4.5.1). I can also serialize these values successfully (I'm the one setting the Flags value, which in this case is a magic number for Consul), it's only deserialization that fails.

The exception I'm getting is: `Newtonsoft.Json.JsonReaderException : JSON integer 16210313421097356768 is too large or small for an Int64. Path '[0].Flags', line 1, position 112.`

The stack trace (not including my callsite) is:
```
           at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)
           at Newtonsoft.Json.JsonTextReader.ParseValue()
           at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
           at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(JsonObjectContract contract, JsonProperty containerProperty, JsonReader reader, Type objectType)
           at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(JsonReader reader, JsonObjectContract contract, JsonProperty containerProperty, ObjectConstructor`1 creator, String id)
           at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
           at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
           at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
           at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
           at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
           at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
```

**Comment by JamesNK** [comment]
See https://github.com/JamesNK/Newtonsoft.Json/pull/892

It will be fixed at some point.

**Comment by highlyunavailable** [comment]
Is there any workaround?

**Comment by JamesNK** [comment]
Deserialize to a string and convert it yourself.

**Comment by highlyunavailable** [comment]
That is not possible - I get this error even if the datatype to deserialize to is a string. The exception is thrown in the parser (see stack trace and the PR you referenced when closing this) and so the data never even gets to an upper layer where it can be mapped into a string property.

**Comment by JamesNK** [comment]
That's a bug I've fixed recently. After the next release you could read it as a string. I don't know when that will be.

**Comment by highlyunavailable** [comment]
Ah, okay. Good to know. I'll just do it that way once the next release happens. Thanks!
