### ISSUE TITLE
"An item with the same key has already been added", if async AJAX request is made

### ISSUE THREAD

**Issue by alexandis** [JamesNK/Newtonsoft.Json#856]
I have simple class that serves to represent error validation messages dictionary in javascript.
Here it is:

    using MyCompany.LoanAdmin.Mvc.Models;
    using MyCompany.Extensions;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Web;
    using MyCompany.LoanAdmin.Mvc.Extensions;
    using MyCompany.Helpers;
    using MyCompany.LoanAdmin.Mvc.Common;
    using MyCompany.LoanAdmin.Mvc.Validation.MessageBuilders;
    using Newtonsoft.Json;
    using System.ComponentModel.DataAnnotations;
    using System.Reflection;
    using MyCompany.LoanAdmin.Mvc.UI;
    using MyCompany.LoanAdmin.Mvc.Helpers.ResourceFormatter;
    using MyCompany.Attributes;
    using MyCompany.LoanAdmin.Mvc.Validation.Manager;

    namespace MyCompany.LoanAdmin.Mvc.Validation { public class ModelValidationErrorMessageStorage {

        public readonly ResourceManager ResourceManager;

        private readonly ResourceHelper resourceHelper;

        private ConcurrentDictionary<string, ConcurrentDictionary<string, ConcurrentDictionary<string, string>>> map = new ConcurrentDictionary<string, ConcurrentDictionary<string, ConcurrentDictionary<string, string>>>();

        public ModelValidationErrorMessageStorage(ResourceManager resourceManager, ResourceHelper resourceHelper) {
            this.ResourceManager = resourceManager;
            this.resourceHelper = resourceHelper;
        }

        public string ToJson() {
            return JsonConvert.SerializeObject(this.map);
        }

        public string GetErrorMessage(string entityName, string propertyName, string validationName) {
            if (!this.map.ContainsKey(entityName)) {
                return String.Empty;
            }

            if (!this.map[entityName].ContainsKey(propertyName)) {
                return String.Empty;
            }

            if (!this.map[entityName][propertyName].ContainsKey(validationName)) {
                return String.Empty;
            }

            return this.map[entityName][propertyName][validationName];
        }

        public void Register<TEntity>() where TEntity: new() {
            string entityName = GetEntityName<TEntity>();

            this.map.GetOrAdd(entityName, this.GetEntityPropertiesValidationMap<TEntity>());
        }

        public void AddValidation<TEntity>(Expression<Func<TEntity, object>> property, ValidationAttribute attribute) where TEntity: new() {
            this.Register<TEntity>();
            string entityName = GetEntityName<TEntity>();
            string propertyName = TypeOf<TEntity>.GetFlattenPropertyName(property);
            string localizedPropertyName = this.resourceHelper.GetPropertyHeaderText(property);

            AddValidationMessage(this.map[entityName][propertyName], localizedPropertyName, attribute);
        }

        private void AddValidationMessage(ConcurrentDictionary<string, string> validationMap, string propertyName, ValidationAttribute attribute) {
            var validationName = GetValidationName(attribute.ToHtmlAttribute("").Name);
            var formatter = this.GetFormatterForAttribute(attribute);
            var message = formatter.GetMessageFor(propertyName);

            AddValidationMessage(validationMap, validationName, message);
        }

        private ConcurrentDictionary<string, ConcurrentDictionary<string, string>> GetEntityPropertiesValidationMap<TEntity>() {

            var entityPropertyMap = new ConcurrentDictionary<string, ConcurrentDictionary<string, string>>();

            foreach (var propertyExpression in GetEntityProperties<TEntity>()) {
                entityPropertyMap.GetOrAdd(
                    TypeOf<TEntity>.GetFlattenPropertyName(propertyExpression),
                    this.GetPropertyValidationMessages(propertyExpression));
            }

            return entityPropertyMap;
        }

        private ConcurrentDictionary<string, string> GetPropertyValidationMessages<TEntity>(Expression<Func<TEntity, object>> propertyExpression) {
            var validationMap = new ConcurrentDictionary<string, string>();

            string localizedPropertyName = this.resourceHelper.GetPropertyHeaderText(propertyExpression);

            foreach (var attribute in propertyExpression.GetValidationAttributes()) {
                this.AddValidationMessage(validationMap, localizedPropertyName, attribute);
            }

            if (propertyExpression.IsKeyProperty()) {
                var keyFormatter = this.GetKeyFormatter<TEntity>();

                string propertyName = TypeOf<TEntity>.GetFlattenPropertyName(propertyExpression);
                AddValidationMessage(validationMap, GetValidationName(Constants.Attributes.IsUniqueMethod), keyFormatter.GetMessageFor(propertyName));
            }

            return validationMap;
        }

        private static void AddValidationMessage(ConcurrentDictionary<string, string> validationMap, string validationName, string message) {
            validationMap.GetOrAdd(validationName, message);
        }

        private static string GetValidationName(string htmlAttributeName) {
            return htmlAttributeName.Replace("data-", String.Empty);
        }

        private static string GetEntityName<TEntity>() {
            return typeof(TEntity).Name;
        }

        private static IEnumerable<Expression<Func<TEntity, object>>> GetEntityProperties<TEntity>() { 
            var parameter = Expression.Parameter(typeof(TEntity), "x");

            return typeof(TEntity)
                .GetProperties(BindingFlags.Instance | BindingFlags.Public | BindingFlags.DeclaredOnly)
                .Select(pi => Expression.Lambda<Func<TEntity, object>>(
                    Expression.Convert(Expression.Property(parameter, pi.Name), typeof(object)), parameter))
                .ToList();
        }

        private ValidationMessageFormatter GetKeyFormatter<TEntity>() {
            var keyProperties = HtmlExtensions.GetKeyProperties<TEntity>();

            return new UniquenessFormatter(
                keyProperties.Select(expr => this.resourceHelper.GetPropertyHeaderText(expr)),
                this.ResourceManager
            );
        }

        private ValidationMessageFormatter GetFormatterForAttribute(ValidationAttribute attribute) {
            if (attribute.GetType() == typeof(RequiredAttribute)) {
                return new RequiredFormatter((RequiredAttribute) attribute, this.ResourceManager);
            }

            if (attribute.GetType() == typeof(MaxLengthAttribute)) {
                return new MaxLengthFormatter((MaxLengthAttribute) attribute, this.ResourceManager);
            }

            if (attribute.GetType() == typeof(MinLengthAttribute)) {
                return new MinLengthFormatter((MinLengthAttribute) attribute, this.ResourceManager);
            }

            if (attribute.GetType() == typeof(PositiveDoubleNumberAttribute)) {
                return new PositiveDoubleFormatter((PositiveDoubleNumberAttribute) attribute, this.ResourceManager);
            }

            if (attribute.GetType() == typeof(PositiveIntegerNumberAttribute)) {
                return new PositiveIntegerFormatter((PositiveIntegerNumberAttribute) attribute, this.ResourceManager);
            }

            if (attribute.GetType() == typeof(RangeAttribute)) {
                return new RangeFormatter((RangeAttribute) attribute, this.ResourceManager);
            }

            if (attribute.GetType() == typeof(RegularExpressionAttribute)) {
                return new RegexFormatter((RegularExpressionAttribute) attribute, this.ResourceManager);
            }

            if (attribute.GetType() == typeof(LessThanOrEqualToAttribute)) {
                return new LessThanOrEqualToFormatter((LessThanOrEqualToAttribute) attribute, this.ResourceManager);
            }

            if (attribute.GetType() == typeof(GreaterThanOrEqualToAttribute)) {
                return new GreaterThanOrEqualToFormatter((GreaterThanOrEqualToAttribute) attribute, this.ResourceManager);
            }

            throw new NotImplementedException("Unknown validation attribute: " + attribute.GetType().Name);
        }
    }}

The instance of this class is created with my page's model each time (including both GET and POST requests - because the model is re-created each time), since each page method may theoretically add / remove some messages from the dictionary. It's done in the following way:
`this.ValidationMessageStorage.Register<TEntity>()` inside page model's constructor.
Everything works properly, except situation, when I call AJAX page count method, which calculates TOTAL number of records existing for given entity. Page model is created there, too - so the message dictionary.
And now - weird thing: when i comment record count method call in my javascript - everything is fine.
If it's called - EVEN IF I PUT BREAKPOINT at its first line - still before it's called, the following EXCEPTION happens:

    "An item with the same key has already been added"
    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
    at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
    at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
    at System.Web.Mvc.JsonValueProviderFactory.EntryLimitedDictionary.Add(String key, Object value)
    at System.Web.Mvc.JsonValueProviderFactory.AddToBackingStore(EntryLimitedDictionary backingStore, String prefix, Object value)
    at System.Web.Mvc.JsonValueProviderFactory.AddToBackingStore(EntryLimitedDictionary backingStore, String prefix, Object value)
    at System.Web.Mvc.JsonValueProviderFactory.AddToBackingStore(EntryLimitedDictionary backingStore, String prefix, Object value)
    at System.Web.Mvc.JsonValueProviderFactory.GetValueProvider(ControllerContext controllerContext)
    at System.Web.Mvc.ValueProviderFactoryCollection.GetValueProvider(ControllerContext controllerContext)
    at System.Web.Mvc.ControllerBase.get_ValueProvider()
    at System.Web.Mvc.ControllerActionInvoker.GetParameterValue(ControllerContext controllerContext, ParameterDescriptor parameterDescriptor)
    at System.Web.Mvc.ControllerActionInvoker.GetParameterValues(ControllerContext controllerContext, ActionDescriptor actionDescriptor)
    at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)

I was unable to understand, why - no any breakpoints in ModelValidationErrorMessageStorage get hit. I suppose it has something to do with async ajax call and some non-thread-safe operations within my class, but not sure...
UPDATE: weird, but it works properly on other pages, however the same ajax request and common model creation approach is the same. Maybe you have idea what could be wrong?

**Comment by alexandis** [comment]
It looks like it's not directly related to JSON serialization... Weird issue.
