### ISSUE TITLE
InvalidCastException When Populate Object

### ISSUE THREAD

**Issue by diegohoyos** [JamesNK/Newtonsoft.Json#885]
There is a strange case of invalid conversion when try to populate a object with nullable double property. 
When you send numbers from javascript usign JSON.Stringify you get a string representation while the precision is less than 22 digits, starting with 22 digits you get 1E+21.
JSON.Net can convert strings correctly until 19 digits and works fine with 1E+? representation, but when you have a number of 20 or 21 digits you get an exception of type System.InvalidCastException: Unable to cast object of type 'System.Numerics.BigInteger' to type 'System.IConvertible'.

You can reproduce this behavior with the next code.

class Editor {
     public double? MaxValue { get; set; }
}
var jObject = Newtonsoft.Json.Linq.JObject.Parse("{ maxValue:10000000000000000000}");
var serializer = new Newtonsoft.Json.JsonSerializer();
var target = new Editor();
serializer.Populate(jObject.CreateReader(), target);

System.InvalidCastException: Unable to cast object of type 'System.Numerics.BigInteger' to type 'System.IConvertible'.
   at System.Convert.ToDouble(Object value, IFormatProvider provider)
   at Newtonsoft.Json.JsonReader.ReadAsDouble()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.Populate(JsonReader reader, Object target)

**Comment by JamesNK** [comment]
Fixed https://github.com/JamesNK/Newtonsoft.Json/commit/5b04a61dd9b5782af45842da254f15bf3cbfd0b7
